yalelibrary/yul-dc-blacklight

config/blacklight.yml

Let's use solr core names blacklight-development and blacklight-test so it will be clear that we have different environments during development.

Align solr names with yul-dc-solr

---

docker-compose.yml

We need one solr instance for development, and one for test.

Build two solr cores

---

.env

The `.env` file is out of date after the renaming of the Solr cores.   Fixes #6

Change .env to reference development Solr core.

---

Dockerfile
docker-compose.yml
ops/webapp.conf

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/61
Running `docker-compose up web` should bring up all the services we need for the blacklight app
The docker-compose.yml file lists all of the yul-dc services:
- db
- images
-  manifests
- blacklight (listed as "web")
- solr
We may need to come back to the ports on some of the services at a later date. They all work for now though.

i61-blacklight-app-services

---

app/services/voyager_indexing_service.rb
spec/services/voyager_indexing_service_spec.rb

Blacklight will need the metadata from voyager plus the oid from ladybird in order to display records properly.
Connected to https://github.com/yalelibrary/YUL-DC/issues/89

Add oid from ladybird to solr records

---

lib/tasks/index_sample_data.rake

The `load_voyager_sample_data` now needs to set `ladybird_metadata_path` as the indexing service uses the ladybird data to get the oid.

Add ladybird_metadata_path to the load_voyager_sample_data rake task

---

app/services/voyager_indexing_service.rb
app/views/catalog/_show_links.html.erb
app/views/catalog/_uv.html.erb
spec/services/voyager_indexing_service_spec.rb
spec/views/catalog/_show_links.html.erb_spec.rb

This PR assumes that the docker contain was built previously.  
- Get branch 
Once the branch has been pulled:  
run the following rake task:
- rake yale:clean_solr
after running the rake task, confirm locally zero objects on the website, then run the following rake task to add the objects. 
- rake yale:load_voyager_sample_data
Once the objects are added, confirm locally 45 items in on the website.  
(There are images on Zenhub: https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/97)

97 ensure all samples discoverable

---

README.md
docker-compose.yml

This PR:
* adds .env.development to docker-compose.yml
* adds info on .env.development to README
Current .env has localhost, presumably for ECS? This helps devs override.

Support .env.development for overrides

---

app/assets/javascripts/uv_width.js
app/assets/stylesheets/uv.css
app/views/catalog/_uv.html.erb
config/uv/uv.html

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/114
When I'm viewing a multipage work, I would like a thumbnail view of all the pages, so that I can quickly scan and jump through long works, instead of having to navigate one page at at time.
- user's see thumbnails of all images in the left pane **when the browser window is 1200px or wider**
- user's can click the gallery view option in the top pane
- https://github.com/emory-libraries/dlp-lux/pull/93
- https://forum.omeka.org/t/universal-viewer-config-json/9451

i114-display-images-tray

---

.rubocop_todo.yml
app/services/voyager_indexing_service.rb
spec/system/view_facet_spec.rb
spec/system/view_fields_in_display_spec.rb
spec/system/view_fields_in_search_spec.rb

----
**For ticket 128**
1. git pull 
2. reindex Solr with the rake task `rake yale:load_voyager_sample_data`
3. then bring up the server and verify on local that the format facet appears on the lefthand side.  
**Continue testing for ticket 129**
4. complete a search
5. verify format field is under each item
**Lastly, testing for ticket 130**
6. click on an object to verify formatting is below image

add format to Solr indexing for tickets 128-130

---

.circleci/config.yml
app/controllers/catalog_controller.rb
app/services/voyager_indexing_service.rb
spec/system/view_fields_in_display_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/144
As a scholar, I would like to see all the available descriptive metadata about a work, so that I can better understand the work's context.
When viewing a work that has the fields below, they will show up on the page:
- abstract
- alternativeTitle
- genre
- geoSubject
- resourceType
- subjectName
- subjectTopic

i144-title-and-keywords-fields

---

.github/workflows/dockerimage.yml
README.md
app/controllers/catalog_controller.rb
spec/system/view_fields_in_display_spec.rb

Co-authored by [Frederick Rodriguez](frederick.rodriguez@yale.edu)
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/147
As a scholar, I'd like to filter out results from my searches that aren't completely digitized, so that I can identify resources that I can access online in their entirety.
- There is a facet field for 'extentOfDigitization'
- Search results display the 'extentOfDigitization' when available
- Single item view pages display the 'extentOfDigitization' when available
The `extentOfDigitization_ssim:` field in `voyager_indexing_service.rb` will need to be mapped to the correct path by the management team to make this work show up in production

i147-extent-of-digitization-facet

---

app/controllers/catalog_controller.rb
spec/system/view_fields_in_display_spec.rb

Relates to Ticket #148 
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/148
Adds following fields to single item view:
rights
publicationPlace
sourceCreated
publisher
copyrightDate
Screen shot of single item view:

adds publication and rights fields and specs

---

app/controllers/catalog_controller.rb
spec/system/view_fields_in_display_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/145
As a scholar, I would like to see all the available descriptive metadata about a work, so that I can better understand the work's context.
When viewing a work that has the fields below, they will show up on the page:
- oid
- identifierMfhd
- identifierShelfMark
- box
- folder
- orbisBibId
- orbisBarcode
- findingAid
- collectionId
- edition
- uri

i145-identifiers-on-single-item-view

---

Dockerfile
Gemfile
Gemfile.lock

At some point when we re-built the base image we seem to have grabbed an updated version of phusion/passenger-ruby26, which included an upgrade from ruby-2.6.5 to ruby-2.6.6 and now we're getting a ruby version mis-match. Let's upgrade our application to ruby-2.6.6 to match the expectations of the base image.

Upgrade to ruby-2.6.6

---

docker-compose.yml

We inadvertently broke the connection between the local filesystem and the running blacklight application, which prevents using a local editor for development.

Fix local mount

---

Dockerfile
Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
docker-compose.yml
spec/system/view_fields_in_display_spec.rb
spec/system/view_fields_in_search_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/179
The "Title" label for each search result is redundant
- The "Title" label and text on the search results page is gone
- The "Title" label and text on the individual result page is gone
- Users can still search according to the "Title" when you click the "All Fields" dropdown
- Tests for the "Title" field have been removed
- search results page
- individual result page

i179-remove-title-label-from-search-results

---

app/controllers/catalog_controller.rb
spec/system/view_fields_in_display_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/194
On the show page the value in the format field is a link to the facet of works with the same format
should link to something like

194 Added link on format to its facet

---

app/controllers/catalog_controller.rb
spec/system/view_facet_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/192
Added a Resource Type facet
- User's can filter by Resource Type
- Included the Resource Type in the facet's spec

i192-resource-type-facet

---

app/controllers/catalog_controller.rb
spec/system/view_facet_spec.rb

Related to ticket # 193, Add Publication Place facet.
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/193

adds publication place facet and spec

---

app/controllers/catalog_controller.rb
spec/system/view_facet_spec.rb

Related to Ticket #190, Add Author facet
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/190
Testing needs to be done w/ the new management app code to fully ensure functionality with the new author_ssim field.  An additional PR will be needed to update the facet field for author full name. After adding the author_ssim field the search will look like this.

190 add author facet

---

Gemfile.lock
config/initializers/deprecation.rb

Looked further at Shopify’s `deprecation_toolkit` gem with another senior dev. We could not get it to write out its recorded config files. Also it’s very tied to tests, as opposed to a more general case of “all output”.
The reason turns out to be that Blacklight uses it’s own gem for generating deprecations, not the ActiveSupport one. So the Shopify gem doesn’t work here.
BUT there is a configuration option for the Blacklight `deprecation` gem that silences all of them. So I’ve done that. Please note:
1. It’s all or nothing, at least with respect to deprecations generated from Blacklight.
2. It doesn’t affect non-Blacklight deprecations
3. It’s can’t silence anything that is thrown before the initializer is loaded to configure it.

Silence deprecations from Blacklight

---

README.md
app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/210
As a researcher, I'd like an easy way to get to the catalog record for the work I'm looking at. There's a link that takes me to Orbis from the Orbis Bib ID field. The link points to a handle that redirects to the correct catalog record in Orbis

Link the Orbis Bib ID to the Orbis catalog record

---

app/controllers/catalog_controller.rb

During merge the author_tsim was retained.  This was not the desired effect and has been removed and fully replaced by the author_ssim field for the author facet.  The author_tsim field is retained only for the show field and will remain indexable so each word in the author field is able to be searched for.

Remove duplicate author facet

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/helpers/blacklight_helper_spec.rb
spec/system/view_images_in_search_spec.rb

**ACCETPANCE**
When showing search results, 
**Testing**
1. Do an empty search
2. Verify that thumbnails for public works are displayed if they have images, as shown below:

Add thumbnails for public works in search

---

app/controllers/catalog_controller.rb
spec/system/view_facet_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/238
Sometimes when you click the link on an individual show page it shows a human readable string and sometimes it shows the solr field label
Some of the values on an individual show page are created as links by using the `link_to_facet` field. When this link is clicked it does a search based off of that value. If the value is not listed as a facet, then you'll see the solr field label as the search result
- All filtered fields, whether it's a facet from the main search page or a link from the individual show page, have the ability to be shown as a human readable string
- As we convert more values into searchable fields, a corresponding facet will need to be created with a `show: false` value
- …

Search filters display user friendly names

---

.circleci/config.yml

Running our rspec suite in parallel (copied from https://github.com/samvera-labs/samvera-circleci-orb/blob/master/src/commands/parallel_rspec.yml) cuts time to run the tests from ~2 minutes to ~1 minute. This is going to become increasingly important as we grow our test suite and it takes longer and longer to run.

Run rspec in parallel to speed up CI runs

---

.circleci/config.yml

There's built-in support for the COVERALLS_REPO_TOKEN name at the stage when tests are run. https://docs.coveralls.io/supported-ci-services

Use only one name for the coveralls token

---

.github_changelog_generator
CHANGELOG.md
README.md

* By tagging PRs with Feature and Bug labels, we can automate marking them as such in the release notes.
* This will shorten and simplify the release process.
* Update README to reflect updated practice.
Connected to https://github.com/yalelibrary/YUL-DC/issues/296

Further automate generating release notes

---

app/controllers/omniauth_callbacks_controller.rb
spec/controllers/omniauth_callbacks_controller_spec.rb

Purpose is to modify the redirect after a user logs in to either direct them to the page they were on before logging in or to redirect to the home page when that information is not available.  Also adds spec file for the omniauth callbacks controller.
This should be deployed and tested with CAS authentication before merging this code in.

Modify auth redirect and add tests

---

app/assets/stylesheets/blacklight.scss
app/assets/stylesheets/customOverrides/footer.scss
app/assets/stylesheets/customOverrides/header.scss
app/assets/stylesheets/helpers/breakpoints.scss
app/assets/stylesheets/theme/colors.scss
app/assets/stylesheets/theme/typography.scss

Co-authored by: Kait Sewell <kait@notch8.com>
Ticket:
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/319
- Adds Yale branded colors as variables
- Adds Yale branded typefaces as variable
- Adds breakpoints as variables
- Sets up the structure for mobile first design in the header and footer sass files.

Add Yale branded typefaces and colors

---

app/assets/stylesheets/blacklight.scss
app/controllers/catalog_controller.rb
app/models/search_builder.rb
spec/system/highlight_in_search_spec.rb

This PR adds highlighting to Solr queries. Currently the only field that is highlighted is the author field.
Go to http://localhost:3000 and search for an author that exists (e.g. "Jane"). It has to be a full term i.e. "Jane" instead of "Ja" since author searches for full matches of terms.
Verify that the author field is highlighted as shown below:

Setup Solr Highlighting for show fields

---

Gemfile.lock

Noticed that spinning up the current master locally updated the Gemfile.lock with apparition and axe-matchers dependencies. I thought we might want to commit these unless we are specifically ignoring the lock file.

Bundle accessibilty test dependencies

---

app/views/catalog/_show_links.html.erb
app/views/catalog/_uv.html.erb

Adds an alt tag for the IIIF logo image.  Adds an external relation to the IIIF logo link.  Adds a title to the UV iframe.  Relates to ticket #332 - adding names and labels to elements that were failing accessibility testing.

Add names and labels to elements for accessibility

---

app/assets/stylesheets/customOverrides/header.scss
app/assets/stylesheets/customOverrides/main.scss
app/assets/stylesheets/theme/colors.scss

Improve the default color contrast to include the Yale color palette and to improve accessibility.
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/331

Improve color contrast for accessibility

---

app/controllers/catalog_controller.rb
spec/system/view_fields_in_search_spec.rb

Add fields to and remove fields from the displayed fields in the search results view.
[#384](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/384)
Search results should display the following fields (when they have data):
Image Count field is added but not viewable as it is a new field and not yet present in the indexed metadata.

Change displayed search result fields

---

app/assets/stylesheets/customOverrides/footer.scss
app/assets/stylesheets/customOverrides/header.scss
app/assets/stylesheets/customOverrides/main.scss
app/assets/stylesheets/customOverrides/search_result.scss
app/assets/stylesheets/helpers/breakpoints.scss

Co-authored by: Frederick Rodriguez <frederick.rodriguez@yale.edu>
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/402
The new, longer Yale logo gets chopped off when the screen is between 768 px and 1200 px.
- The header image is properly sized across screen from 375 px wide and up
- The additional header links convert to a hamburger menu on x-small and small devices
- The additional header links drop beneath the logo on medium and large devices
- The additional header links show inline on x-large devices

Make the header responsive

---

README.md

The Camerata readme has instructions for cluster and deployment releases. Should those be included in this blacklight readme or is that specific to Camerata?

Added camerata instructions to blacklight readme

---

CHANGELOG.md
app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

**ACCEPTANCE**
* abstract
* alternativeTitle
* alternativeTitleDisplay
* bibId_ssim
* contents
* contributor
* contributorDisplay
* creator
* creatorDisplay
* description
* publicationPlace
* publisher
* sourceCreator
* sourceTitle
* subjectGeographic
* subjectName
* subjectOccupation
* subjectTitle
* subjectTitleDisplay
* subjectTopic
* title
* titleStatement_ssim
*NOTE: We'll do another pass on field mappings closer to release and make sure we catch anything that was in flux between the Metadata Cloud, Management App, and Discovery App - so if we don't get 100% of fields in right now, that's ok, we just want to get as many as we can so we have representative support for UI and UX design.

Update allfields search behavior 388

---

app/controllers/catalog_controller.rb
spec/system/highlight_in_search_spec.rb
spec/system/view_fields_in_search_spec.rb

**STORY**
The current [Beinecke site](https://brbl-dl.library.yale.edu/vufind/Search/Results?lookfor=baldwin&type=AllFields&submit=Find&limit=16&sort=relevance) site provide match highlighting.  We want the new system to have this capability too.
**ACCETPANCE**
Highlight search matches when they occur on the following fields:
-----
We were able to implement the highlighting for resource type and identifier shelfmark.

Add highlighting to search result

---

app/controllers/catalog_controller.rb
spec/system/highlight_in_search_spec.rb

Decide which fields highlighting should be implemented and add that functionality.
**ACCEPTANCE**

338 title result highlighting

---

app/assets/stylesheets/customOverrides/footer.scss
app/assets/stylesheets/customOverrides/header.scss
app/views/shared/_footer.html.erb
spec/system/footer_spec.rb

Co-authored by: Frederick Rodriguez <frederick.rodriguez@yale.edu>
The footer logo, links and social media icons don't display correctly on any screens smaller than 1700 px wide. The details either overlap, or are cut off
- on devices 767px and smaller, all footer elements are stacked vertically, including the footer links
- on devices 768 px to 1199 px wide, the footer elements are stacked vertically but the links are in a row
- on devices 1200px and wider, the yale logo and links are in the same row. the social media links are beneath the yale logo
- the "branch" info isn't always aligned with the other content to keep it out of the way since it will be deleted
- clicking the yale logo in the footer redirects to the home page
- hovering over the yale logo in the footer doesn't display …

Make the footer responsive

---

app/views/shared/_footer.html.erb
spec/system/footer_spec.rb

Add alt tags to social media icons in footer.
[#400](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/400)

Add alt tags to social media icons

---

app/views/catalog/_search_form.html.erb

Add an aria label on the search form
[#391](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/391)

Add an aria label to search form

---

app/views/shared/_header_navbar.html.erb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/414
- When a user clicks on a submenu link on devices smaller than 1200px wide, it only displays a blue box underneath the selected menu item
- When a user clicks on a submenu item on devices 1200px wide and greater, it still displays a blue box underneath all links

Fix header content height on condensed view

---

app/views/catalog/_show_main_content.html.erb
app/views/catalog/_show_sidebar.html.erb

Move the tools and links from the top right hand corner to below the metadata information on the single item show page.
#427
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/427

Relocate tools and links to bottom of page

---

app/controllers/catalog_controller.rb
spec/system/user_authentication_spec.rb

We've decided to remove the ability to retrieve bookmarks and removed the corresponding link from the header, but we still have bookmark checkboxes displaying in search results.  This gives the incorrect impression that users can save bookmarks within the application to retrieve later.
**ACCETPANCE**

Removed bookmark checkbox on research and item page

---

app/controllers/catalog_controller.rb
spec/system/highlight_in_search_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/422
- The "Title" property doesn't show up in search results
- The highlighting spec doesn't reference the "Title"

Remove duplicate title listing

---

app/assets/stylesheets/customOverrides/search_result.scss
spec/system/search_result_spec.rb

In Safari, there is excess whitespace between the title and the metadata on the search results screen

Remove excess whitespace in Safari

---

app/assets/stylesheets/customOverrides/facets.scss

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/428
- 'Limit your search' has a font weight of 900, but is not as bold as in the design because we don't have the Mallory Black font
- 'Limit your search' is in the Mallory Medium font
- Facet headers are in the Mallory Medium font
- The facet titles and drop down items match the look of the design, but aren't the exact font-sizes in the design. If they were, they'd be too small
- Reduced the space between facet headers. It isn't exactly 16px between them though because the styles that were inherited from the blacklight app are set with `!important` so they can't be overridden.

Facet styling

---

package.json
yarn.lock

See https://github.com/advisories/GHSA-hxcc-f52p-wc94
The fix is to upgrade serialize-javascript to ^3.1.0

Security fix for CVE-2020-7660

---

.github_changelog_generator
README.md
lib/tasks/release.rake

* Decide on the next version number based on whether any closed PRs had a "Feature" label
* Auto-generate the release notes using the settings the project previously agreed on
* Auto-tag the release, using the new version number and generated release notes
Connected to https://github.com/yalelibrary/YUL-DC/issues/440
Co-authored-by: Rachel Kadel <rachel.kadel@curationexperts.com>
Co-authored-by: Jez Go <jez@notch8.com>

Automate tagging a release

---

app/assets/stylesheets/customOverrides/main.scss
app/views/catalog/_show_main_content.html.erb
app/views/catalog/_show_sidebar.html.erb

The tools in the sidebar were moved below the main content but a bug was introduced - the settings, gallery, and more information elements in the UV viewer were unable to be selected because the sidebar was still covering that section.
A user can now select the UV settings that were previously unable to be selected.
On hover now that the elements are able to be selected again a user can see the gallery and settings options for the UV viewer.

Enable selection of UV settings

---

README.md

Over the past few weeks some of us have had issues with getting the management app to load. The solution typically requires a change to either the blacklight or management app. The changes to the README that I've added today fixed it for me, but may need to be updated as the state of the apps are constantly changing.

Add management app troubleshooting to README

---

Gemfile
Gemfile.lock
app/assets/javascripts/blacklight_gallery.js
app/assets/javascripts/openseadragon.js
app/assets/stylesheets/blacklight_gallery.css.scss
app/assets/stylesheets/openseadragon.css
app/controllers/application_controller.rb
app/controllers/catalog_controller.rb
app/models/solr_document.rb

Co-authored-by: Alisha Evans <alisha@notch8.com>
As a scholar, I'm interested in the visual characteristics of works, and would like to be able to view search results in a way that allows me to see more thumbnails on the screen at one time
**DEVELOPER HINT**
Implemented the [Blacklight Gallery](https://github.com/projectblacklight/blacklight-gallery#blacklightgallery) gem.
**ACCEPTANCE**

Added the Blacklight Gallery view

---

app/assets/stylesheets/customOverrides/facets.scss
app/assets/stylesheets/customOverrides/footer.scss
app/assets/stylesheets/customOverrides/header.scss
app/assets/stylesheets/customOverrides/pagination.scss
app/assets/stylesheets/theme/typography.scss

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/472
- Add placeholders for the MalloryMP-Medium and MalloryMP-Black fonts
- The above two fonts currently point at the Mallory-Medium font
- Updated the all Mallory versioned fonts in use to fallback to Arial then Helvetica then sans-serif
- Updated the Yale fonts in use to fallback to Times New Roman then Times then serif

Add font-family fallbacks

---

app/assets/stylesheets/customOverrides/show_page.scss

Adds space between text and caret.
Zeplin
Firefox pre edit
In this PR

Adds styling to tools and links

---

app/assets/stylesheets/customOverrides/search_result.scss
app/views/catalog/_index_header.html.erb
spec/system/highlight_in_search_spec.rb
spec/system/sort_in_search_spec.rb

We did have search term highlighting in the title working (https://github.com/yalelibrary/YUL-DC/issues/338), but it seems to have stopped working when we removed the extra title from the search results metadata (https://github.com/yalelibrary/YUL-DC/issues/422). See screenshot below.
----

Search term highlighting in title

---

app/views/catalog/_home_text.html.erb

This commit overrides blacklight's default homepage partial so we can
provide Yale specific messaging.
At this point, we're providing some weclome text to help users of the
internal preview to get started exploring. The page also describes how
to use BugHerd to send feedback to the development team.

Update the welcome message on the homepage

---

app/assets/stylesheets/customOverrides/show_page.scss

Include IIIF logo and link under Links at bottom of single item view page.
**Current View**
**Proposed View**
**ACCEPTANCE:**
Related to: https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/478

Added Include IIIF Logo to Show page

---

app/controllers/catalog_controller.rb

**STEPS TO REPRODUCE**
1. Go to any system running v.1.15.1 (e.g. https://collections-test.library.yale.edu/?search_field=all_fields&q= )
2. Click on search (search for all items)
3. Expand the "Publication Date" facet
4. *Use the mouse* to slide the upper date limit about 1/4 of the way earlier (i.e. from around 2020 --> 1775)
5. Click on "Apply"
**EXPECTED RESULT**
**ACTUAL RESULT**
**STEP 3**
**STEP 4**
**Bug Behavior**
**Expected Behavior**
https://share.getcloudapp.com/12uJdQzJ

Fixed publication date slider bug

---

app/assets/stylesheets/customOverrides/show_page.scss

Adds styling to single item show page metadata block 
#477 [ZenHub Link](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/477)

Styles single item show page metadata

---

app/assets/stylesheets/customOverrides/pagination.scss

Styles the bottom pagination on the search results page
#531 [ZenHub Link](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/531)
https://share.getcloudapp.com/Jru6Yre2

Adds styling to search results bottom pagination

---

app/assets/stylesheets/customOverrides/search_result.scss
app/views/catalog/_search_results.html.erb

Adds styling to search results list view.
#465 [ZenHub Link](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/465)
* A bug was introduced that overlapped the metadata on the search result list view
* This PR fixes that bug and moves closer to the intended design
* This PR does not 1-1 match the design and is aimed to fix the overlapping metadata bug
* See below for what the previously rendered the search results list view looked like
https://share.getcloudapp.com/o0u80LKG

Fix metadata overlap on search results list view

---

app/assets/stylesheets/customOverrides/index_gallery.scss
app/assets/stylesheets/customOverrides/show_page.scss
app/views/catalog/_show_main_content.html.erb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/565
- the gallery view of search results remains styled as the design intends
- the list view of search results looks like it did out of box, besides the title color being updated
- the yale restricted caption is in line with the title on an individual show page

Return master to releasable

---

app/assets/stylesheets/customOverrides/facets.scss

Facet styling rework to prevent facet count from wrapping to next line.
#462 - [ZenHub Link](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/462)

Prevent facet count wrap

---

app/controllers/catalog_controller.rb
spec/system/search_fields_spec.rb
spec/system/view_facet_spec.rb

Add search by identifier shelf mark

---

app/controllers/catalog_controller.rb
spec/system/search_result_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/515
- in gallery view the "per page" option is 9, 30, 60 and 99
- in list view the "per page" option is 10, 20, 50, 100

Different "per page" option for list and gallery views

---

.rubocop.yml
app/assets/config/manifest.js
app/assets/stylesheets/customOverrides/main.scss
app/assets/stylesheets/customOverrides/pagination.scss
app/views/kaminari/blacklight/_first_page.html.erb
app/views/kaminari/blacklight/_last_page.html.erb
app/views/kaminari/blacklight/_paginator.html.erb
config/locales/blacklight.en.yml
spec/system/search_result_pagination_spec.rb

Continued improvement to bottom pagination 
#531 [ZenHub Link](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/531)

Styles bottom pagination

---

app/views/advanced/index.html.erb
app/views/catalog/_search_form.html.erb
spec/system/advanced_search_spec.rb

_No ticket. Part of the "Sept 17 Yale swarm" doc_
- the second button on the search bar now says "advanced search" instead of "more options"
- when on the advanced search page, it now says "advance search" instead of "more search options"
- the title in the tab on that page also now says "advanced search"

More Options -> Advanced Search

---

app/assets/stylesheets/customOverrides/show_page.scss

On single item show page the previous and next buttons were not clickable because of overlapping elements.  This PR makes them clickable again.
https://share.getcloudapp.com/5zuGxDmE

Positions context search above blocking elements

---

app/views/shared/_header_navbar.html.erb

_No ticket. Part of the "Sept 17 Yale swarm" doc_
- the search bar does not show up on the "advanced search" page
- the search bar shows up on all other pages
- https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-current_page-3F
- https://stackoverflow.com/a/30221962/8079848

Remove search bar from the advanced search page

---

app/assets/stylesheets/customOverrides/header.scss

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/588
- arrows in the secondary nav rotate when a link is clicked

Rotate submenu arrows

---

app/assets/stylesheets/customOverrides/header.scss
app/assets/stylesheets/customOverrides/index_gallery.scss
app/views/catalog/_index_header.html.erb
spec/system/search_result_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/575
- searching for a word/phrase will show that word/phrase in the title in list view and gallery view
- https://stackoverflow.com/a/7317016/8079848
- https://stackoverflow.com/a/2165727/8079848

Title highlighting in gallery view works again

---

app/assets/stylesheets/customOverrides/search_bar.scss
app/controllers/catalog_controller.rb
spec/system/advanced_search_spec.rb

Rename all fields to common fields

---

db/migrate/20200923183339_remove_user_email_index.rb
db/schema.rb

CAS does not provide an email address for users, but Devise defines an email field for the User model, and puts an index on it. We should remove the index, since most if not all User objects will have an empty string for their email address.
Connected to https://github.com/yalelibrary/YUL-DC/issues/596

Remove index on User.email field

---

app/assets/stylesheets/customOverrides/subheader_users.scss
app/views/shared/_user_subheader.html.erb
spec/system/subheader_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/560
- Additional spacing between the bar underneath the Digital Collections row and the "Limit your search" text
- Additional spacing between the Digital Collections text and the search bar above it
- The grey line underneath the Digital Collections row right aligns with the gallery view box beneath it
- The icons for the user net id and log out options on the Digital Collections row have been commented out

Digital Collections row styling

---

app/assets/stylesheets/customOverrides/advanced_search.scss
app/views/advanced/_advanced_search_form.html.erb
spec/system/advanced_search_spec.rb

Styles the footer of the advanced search page.
#562 [ZenHub](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/562)

Adds styling and buttons to advanced search footer

---

app/assets/stylesheets/customOverrides/advanced_search.scss
app/controllers/catalog_controller.rb
app/views/advanced/_advanced_search_form.html.erb
app/views/advanced/index.html.erb
spec/controllers/catalog_controller_spec.rb
spec/support/solr_documents/advanced_search_testing_only.rb
spec/system/advanced_search_spec.rb
spec/system/search_fields_spec.rb

Style the body section of the advanced search page
#563 [ZenHub](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/563)

Styles the input and help section of advanced search

---

app/controllers/catalog_controller.rb
spec/system/advanced_search_spec.rb

* Add most fields to the 'Common Fields' input search on the Advanced Search page
* Changes 'Author' label to 'Creator'
#594 [ZenHub](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/594)

Adds fields to advanced search and changes author to creator

---

README.md

Updated the `AWS_PROFILE` instructions in the readme to instruct us on how to set up the profile with our yale credentials instead of our dce credentials

Update readme to reference yale aws profile

---

app/assets/stylesheets/customOverrides/advanced_search.scss
app/assets/stylesheets/customOverrides/search_bar.scss
app/views/advanced/_advanced_search_form.html.erb
app/views/advanced/index.html.erb
app/views/shared/_user_subheader.html.erb
config/locales/blacklight_advanced_search.en.yml
spec/system/advanced_search_spec.rb
spec/system/sort_in_search_spec.rb

Co-authored-by: Frederick Rodriguez <frederick.rodriguez@yale.com>

Style the advanced search header

---

app/controllers/catalog_controller.rb
spec/system/highlight_in_search_spec.rb

**STEPS TO REPRODUCE**
1. Search for "SUBJECT": "Portable Medieval Manuscripts"
**EXPECTED RESULTS**

Added correct solr field for subject topic

---

app/controllers/catalog_controller.rb
spec/system/date_slider_spec.rb

Fixes the above issue of a machine date appearing when results only have one date facet.

Fix date slider for results with only one date facet.

---

app/assets/stylesheets/customOverrides/advanced_search.scss
app/controllers/catalog_controller.rb
app/views/advanced/_advanced_search_form.html.erb
spec/system/advanced_search_spec.rb

Updated the Advanced Search page to reflect the design [in zeplin](https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f5707bfd9b7b87a960b8314)

Advanced search footer styling

---

app/assets/stylesheets/customOverrides/index_gallery.scss
app/assets/stylesheets/customOverrides/search_result.scss
app/views/catalog/_index_header.html.erb
spec/system/search_result_spec.rb

Update the app UI to match Matt Walker's design: https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f0fd3010b521c8d2c66b758
(View the design at 100% when making comparisons to the blacklight app)
External example:  https://digital.library.emory.edu/?utf8=%E2%9C%93&search_field=common_fields&q=
-----
**The Actual UI**
**Mobile**
**Mobile Medium**
**Mobile Large**
**Desktop**

Style search results list view

---

config/locales/submenu.en.yml

The link is not displaying correctly. 
**Current Display on both Test and UAT** 
**Code Fix Display**

Change wording in submenu for course reserve

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
app/views/catalog/_constraints.html.erb
app/views/catalog/_constraints_element.html.erb
spec/support/capybara.rb
spec/system/date_slider_spec.rb

Issue yalelibrary/YUL-DC#549
**STEPS TO REPRODUCE**
1. Go to any system running v.1.15.1 (e.g. https://collections-test.library.yale.edu/?search_field=all_fields&q= )
2. Click on search (search for all items)
3. Expand the "Publication Date" facet
4. *Use the mouse* to slide the upper date limit about 1/4 of the way earlier (i.e. from around 2020 --> 1775)
5. Click on "Apply"
**EXPECTED RESULT**
**STEP 3**
**STEP 4**
**ACTUAL RESULT**
**EXPECTED RESULT**
Something similar to this

Fix date slider bounds and tests. Add date constraint.

---

app/controllers/catalog_controller.rb
spec/system/advanced_search_spec.rb

Co-authored by: JP Engstrom <jp@notch8.com>
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/668
On the Advanced Search page, Replace the label 'Common Fields' with "All Fields"

Return "common fields" to "all fields"

---

app/assets/stylesheets/customOverrides/show_page.scss
app/helpers/blacklight_helper.rb
app/views/catalog/_show_links.html.erb
spec/views/catalog/_show_links.html.erb_spec.rb

Co-authored-by: Martin Lovell <martin.lovell@yale.edu>
Co-authored-by: Maggie Zhao <maggie.zhao@yale.edu>
**ACCEPTANCE**
Mock up (but styling should match existing links)
**ACTUAL IMPLICATION**

Add a link to the mirador viewer in the tools

---

app/controllers/catalog_controller.rb
spec/system/sort_in_search_spec.rb

Issue yalelibrary/YUL-DC#730
Co-authored-by: Martin Lovell <martin.lovell@yale.edu>
Co-authored-by: Frederick Rodriguez <frederick.rodriguez@yale.edu>
Co-authored-by: Maggie Zhao <maggie.zhao@yale.edu>
Co-authored-by: Eric DeJesus <eric.dejesus@yale.edu>
**ACCEPTANCE**

Add Ascending and Descending options for result sorting#730

---

app/controllers/catalog_controller.rb
spec/system/advanced_search_spec.rb

Co-authored-by: Eric DeJesus <eric.dejesus@yale.edu>
The title sort search appears to be working correctly. Currently, the code has a secondary field, pub_date_si, not being used in Solr.

Modified title sort for a more accurate result

---

config/locales/blacklight.en.yml
spec/system/show_page_spec.rb

I've tried this at a number of widths, including cell phone view, and the styling seems good.
Connected to https://github.com/yalelibrary/YUL-DC/issues/725

Change language to "Back to Search Results"

---

app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

As a user, I want to be able to click on the creator name to get a search of the creator.
**Proposed Implementation**  
**Actual Implementation**

Create a link for creator facet

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
config/metadata/origin_metadata.yml
spec/presenters/yul/metadata_presenter_spec.rb
spec/system/view_fields_in_display_spec.rb

As a user, I want to be able to click on the creator name to get a search of the creator.

Link creator facet in show page

---

app/assets/stylesheets/theme/colors.scss

Per Accessibility requirements 
Current Color: 
New Color:

Change color of links on the whole site

---

app/views/catalog/_constraints.html.erb

Remove screen reader-only label that duplicates visible text

---

ops/webapp.conf

This reverts commit e2785e95e7fb68f7dddf0563fa8f1e97c3cd4250.
This change appears to be blocking deployment, see CloudWatch [logs for failed yul-test deployment ](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/yul-dc-test/log-events/blacklight$252Fblacklight$252F3aa465d5cb17496bb7d243b0850f65aa) (not sure how long this link will work)
```
nginx: [emerg] "log_format" directive is not allowed here in /etc/nginx/sites-enabled/webapp.conf:22
```

Revert "Enable x-forwared-for (#380)"

---

app/controllers/catalog_controller.rb

The current code creator field has a link displayed on the result page:  
--------
The code change removes the link from displaying on the result page:

Removed creator field link on result page

---

app/assets/stylesheets/customOverrides/constraints.scss
app/assets/stylesheets/customOverrides/main.scss
app/views/catalog/_constraints_element.html.erb
app/views/catalog/_start_over.html.erb

- Style as button
- Change icon color to match text more closely
- Give blank alt text to images so that image name is not read
Before
After

Start over

---

app/views/application/landing.html.erb

We need to add quotes around collection call numbers to
make sure we only get exact matches instead of partial matches
from other collection call numbers.

Make landing page collections link to exact search matches

---

app/assets/stylesheets/customOverrides/constraints.scss
app/assets/stylesheets/customOverrides/main.scss
app/views/catalog/_constraints_element.html.erb
app/views/catalog/_start_over.html.erb

**DETAILS**
See issue 4 in https://drive.google.com/open?id=1KsZmdBi00ScskmAMffnM1O_N-CnMUZIv
**ACCEPTANCE**

Made Filter and startover buttons

---

app/helpers/catalog_helper.rb
app/views/catalog/_search_results.html.erb
config/locales/blacklight.en.yml

I tried several methods here, including aria-live, role=alert, role=status, etc. There is something in the code which causes it to read the title on load. I decided to lean in to this as a feature instead of trying to redo how each page is announced.

Search results added to title, allowing screen readers to announce result count

---

app/views/advanced/_advanced_search_form.html.erb
app/views/catalog/_search_form.html.erb
app/views/catalog/show.html.erb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/837
- the three buttons at the bottom of the advanced search page now have a role of button (see screenshots below)
- the "back to search results", "search" and "advanced search" buttons at the top of the individual show page now have a role of button (see screenshots below)
- the "start over" button on that same page already had a role of button
| | | |
| --- | --- | --- |
| ![Screen Shot 2020-11-17 at 12 44 44 PM](https://user-images.githubusercontent.com/29032869/99459622-4083d180-28e3-11eb-8edf-7cbc69274dac.png) | ![Screen Shot 2020-11-17 at 12 44 52 PM](https://user-images.githubusercontent.com/29032869/99459657-4e395700-28e3-11eb-9d85-f55d147b20fa.png) | ![Screen Shot 2020-11-17 at 12 45 00 …

Semantic buttons on show page and advanced search

---

app/assets/stylesheets/customOverrides/pagination.scss

**The disable pagination arrows at the bottom should match the height of the enable arrows.**

Add disable arrow sytling to bottom bar pagination

---

app/controllers/concerns/check_authorization.rb
app/controllers/iiif_controller.rb
app/controllers/manifests_controller.rb
config/routes.rb
ops/webapp.conf
spec/requests/iiif_request_spec.rb
spec/requests/manifests_request_spec.rb

This commit adds a new route check-iiif which tests for authorization in whatever way other items test for authorization.
It also adds Nginx configs to allow the Cantaloupe service to be moved to authorized-iiif and for this app to server /iiif.
All upstream image transfer after authorization would then be streamed by nginx and would free the Rails application process.
See https://medium.com/@jefawks3/using-nginx-as-a-multi-step-reverse-proxy-to-authorize-requests-before-serving-content-on-s3-d4094577c60e
Fixes https://github.com/yalelibrary/YUL-DC/issues/708

Implement security for IIIF images

---

app/controllers/manifests_controller.rb
spec/requests/manifests_request_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/705
- if a manifest does not show because it does not have the `visibility_ssi` property, the user gets a 404 error
- if the user is not on campus or logged in with cas, they'll get a 401 error when viewing "yale community only" manifests

Manifests return a 401/404 for unauthorized/not found respectively

---

app/controllers/catalog_controller.rb
spec/presenters/yul/metadata_presenter_spec.rb
spec/system/view_fields_in_display_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/826
the following fields are no longer on the show page. there's no visual verification because only fields with a value were appearing on the show page anyway.
- Subtitle
- Published
- Children
- Import URL
- ISBN
- URL

Remove unindexed solr fields

---

app/controllers/catalog_controller.rb
spec/system/sort_in_search_spec.rb

Add sort by year options to search results

---

app/views/catalog/_show_tools.html.erb
spec/views/catalog/_show_tools.html.erb_spec.rb

The URL of the IIIF Manifest should not have a `.json` extension, to match the value in the `@id` field in the Manifest file itself.

Link to IIIF Manifest without .json extension

---

.gitignore
.rubocop.yml
app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
app/views/catalog/_constraints.html.erb
app/views/catalog/_constraints_element.html.erb
spec/helpers/blacklight_helper_spec.rb
spec/support/capybara.rb
spec/system/date_slider_spec.rb
spec/system/facet_by_year_spec.rb

**STORY**
We initially implemented the date slider on a field that did meet Blacklight Range Limit's data requirements (see https://github.com/projectblacklight/blacklight_range_limit#requirements).  We now have a year field that contains integer data and need to update the date facet.
**ACCEPTANCE**

Connect year_isim to dateslider. Fix dateslider going out of range

---

app/controllers/catalog_controller.rb
app/views/catalog/_index_header.html.erb
spec/system/search_result_spec.rb

This adds a gallery_view? method to catalog and exposes it as a helper method.
gallery_view? checks parameters and session to determine if page is in gallery mode.
This fixes issues with numbers showing up on results page when gallery is displayed because of the session rather than because of the parameter.
It uses the same method to determine the number of items per page options.

Use helper method to better determine if in Gallery view

---

app/assets/stylesheets/customOverrides/landing.scss
app/views/application/landing.html.erb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/913
- the hero image changes on page refresh
- while you won't get the same image back to back, you may get image 1, then image 2 and then image 1 again
- making sure that the new image is not the same as the last one may on occasion take a few seconds as the computation runs again
https://share.getcloudapp.com/6quxYl2J

Change hero image on page refresh

---

.rubocop.yml
app/helpers/blacklight_helper.rb
app/helpers/catalog_helper.rb
app/views/catalog/_show_main_content.html.erb
ops/webapp.conf
spec/system/access_restrictions_spec.rb
spec/system/view_images_in_search_spec.rb

This updates a few places where the IPs were not being checked to determine if a user had access to Yale Only metadata/images.
It also adds the X-Forwarded-For header to the proxy check that goes to blacklight so the IP is passed.

Update yale only check

---

app/assets/stylesheets/customOverrides/header.scss

The main menu in the blacklight app has a drop-down caret.  It has a text cursor.  Since it's a link, it should have a pointer cursor.
The requirements to update:

Update dropdown header caret cursor

---

app/assets/stylesheets/theme/typography.scss

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/948
- all Yale fonts should also display in Firefox and Chrome
- the console in Firefox and Chrome shows a CORS error for the `.ttf` font, but it displays correctly in the browser
- `.ttf` is used in Safari. I've confirmed that Safari's console doesn't show font related errors and the correct fonts display on the website
| | firefox dev edition (check underlined font) | chrome | safari |
| --- | --- | --- | --- |
| before | ![Screen Shot 2020-12-17 at 11 13 52 AM](https://user-images.githubusercontent.com/29032869/102543999-fcfabf80-4068-11eb-9ba3-182f266e07be.png)| <img width="946" alt="Screen Shot 2020-12-17 at 1 15 51 PM" src="https://user-images.githubusercontent.com/29032869/102544749-1ea87680- …

Update font face formatting

---

README.md
app/assets/stylesheets/customOverrides/show_page.scss
app/controllers/catalog_controller.rb
app/controllers/concerns/check_authorization.rb
app/controllers/iiif_controller.rb
app/helpers/access_helper.rb
app/helpers/blacklight_helper.rb
app/helpers/catalog_helper.rb
app/models/search_builder.rb
app/views/catalog/_show_main_content.html.erb
app/views/catalog/show_unauthorized.html.erb
spec/system/access_restrictions_spec.rb
spec/system/metadata_line_breaks_spec.rb
spec/system/view_images_in_search_spec.rb

Hides metadata for items with private or unknown visibility.
Refactors access checking code to consolidate.
Adds helper for restriction information displayed to user when digital is restricted or digital/metadata is restricted.

943 refactor visibility checks hide private metadata

---

app/controllers/catalog_controller.rb
spec/system/metadata_line_breaks_spec.rb
spec/system/view_fields_in_display_spec.rb

As a user, I want to be able to click on a subject term to get a search showing me other things with that associated subject term.
**Before**
**After**

724 subjects clickable show page

---

app/assets/javascripts/application.js
app/assets/stylesheets/customOverrides/header.scss
app/views/application/landing.html.erb
app/views/layouts/blacklight/base.html.erb

Banner is on landing, index, and show pages.
Adds banner to the top of all pages (except mirador viewer, since it is full screen.)

Add banner to top of pages

---

app/controllers/catalog_controller.rb
config/initializers/blacklight_advanced_search_patch.rb
spec/system/advanced_search_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1065
**Acceptance**
Wherever the redirect app adds quotes:

Fix issues with nested and unclosed quotes

---

app/models/concerns/mods_solr_document.rb
spec/requests/catalog_controller_request_spec.rb

Added xlink namespace to mods element.
Updated tests.
Before update, listing records in some browsers (Firefox) displayed an XML error:
http://localhost:3000/catalog/oai?verb=ListRecords&metadataPrefix=oai_mods or
https://collections-test.library.yale.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_mods
After update the XML should appear in HTML format.

1160 mods oai updates

---

config/initializers/oai_security_patch.rb
spec/requests/catalog_controller_request_spec.rb

The system should respect the access control settings on an object.  OAI provider would not generate a DC record; it will act like it doesn't exist.
**Acceptance**
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1179

Use SearchBuilder access for OAI provider

---

Gemfile
Gemfile.lock
app/models/blacklight_dynamic_sitemap/sitemap.rb
app/views/blacklight_dynamic_sitemap/sitemap/show.xml.builder
config/routes.rb
package.json
public/robots.txt
spec/system/sitemap_show_spec.rb

Co-author: Martin Lovell <martin.lovell@yale.edu>
Management Application branch: 
https://github.com/yalelibrary/yul-dc-management/pull/584
**Story**
We'd like users to be able to discover all of the content via Google.  To improve the chances that our content will be indexed, we should offer a sitemap.
**Acceptance**
- For each item, the sitemap includes:

Create a sitemap in Blacklight

---

app/views/blacklight_dynamic_sitemap/sitemap/show.xml.builder
spec/system/sitemap_show_spec.rb

Co-authored-by: Frederick Rodriguez <frederick.rodriguez@yale.edu>
Before:
```
<image>http://localhost/imagepath</image>
```
After:
```
<image:image>
<image:loc>http://localhost/imagepath</image:loc>
</image:image>
```

Update image tag in sitemap

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
app/views/catalog/record/_item_metadata.html.erb

co-author: leaann bradford <leaann@notch8.com>
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1103
- links that are part of a rights statement will be sanitized to only show the `a` tag and `href` atttribute
- that same link will display as a link instead of plain text
- if we desire the same behavior for other fields on the page, the `html_safe_converter` helper can be used
- https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize

1103 rights field escape link

---

app/views/catalog/_uv.html.erb
spec/system/show_page_spec.rb

co-author: alisha evans <alisha@notch8.com>
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1194
- The URL of the IIIF Manifests should not include the .json extension.
| before | after |
|---|---|
|![Screen Shot 2021-04-07 at 10 42 23 AM](https://user-images.githubusercontent.com/50561476/113910737-07fb6c00-978e-11eb-9017-78bbf36eb888.png)|![Screen Shot 2021-04-07 at 10 42 44 AM](https://user-images.githubusercontent.com/50561476/113910766-1053a700-978e-11eb-927a-8595aeb1b78d.png)|

remove json format from UV src

---

app/assets/stylesheets/customOverrides/show_page.scss
app/views/layouts/catalog_result.html.erb

co-author: alisha evans <alisha@notch8.com>
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1103
https://github.com/yalelibrary/yul-dc-blacklight/pull/501
Test branch: `Branch:1103-rights-field-escape-link,Deployed:2021-04-07T13:32:39-04:00 `
Noticed on test that different window lengths make the link in the rights statement behave differently. Either all of the link is clickable, various parts of it are clickable, or none of it is clickable.
The text in question is "WATCH File"
| width | clickable portion of text |
| --- | --- |
| 1700px | WATCH File|
|1648px | WATCH Fi |
|1640px | WATCH F |
| 1591px | WATC |
| 1541px| W |
|1218px | n/a |
| 1055px | WATCH File|
| 753px | WATCH File|
| 376px | WATCH …

1103-rights-field-escape-link-2

---

app/views/catalog/_uv.html.erb
spec/system/show_page_spec.rb

**Issue**
yalelibrary/YUL-DC#1193
**Acceptance**
**Validation**
Compare 
http://localhost:3000/catalog/2012036?child_oid=1052762
to 
http://localhost:3000/catalog/2012036

Add use of child oid as parameter to open uv to specific page

---

app/views/catalog/_search_results.html.erb
app/views/mirador/show.html.erb
spec/system/mirador_spec.rb
spec/system/search_result_spec.rb

Adds `<meta name="robots" content="noindex" />` tag to search results.  Does not include tag in /catalog (with no query).

1204 search results no index

---

app/views/catalog/show.html.erb
config/locales/blacklight.en.yml
config/locales/blacklight_advanced_search.en.yml
spec/system/show_page_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1218
- the button on a show page says "new search" whether there is an active search or not
- I tested this by changing the conditional statement in the code. unsure how to test this otherwise because I seem to always have a `current_search_session`

1218 change "start over" to "new search"

---

app/helpers/blacklight_helper.rb
app/models/concerns/schema_org_solr_document.rb
app/models/solr_document.rb
app/views/catalog/_schema_org_metadata.html.erb
app/views/catalog/_show_main_content.html.erb
spec/models/solr_document_spec.rb
spec/requests/catalog_controller_request_spec.rb

Adds header with schema.org metadata.
View source of page to see metadata:
Json Validated at https://search.google.com/structured-data/testing-tool

1203 Add schema.org metadata to show page

---

config/routes.rb

comments about route order are not clear enough. this makes them more specific and easer to see which comment applies to which routes.

clean up route comments

---

app/assets/stylesheets/customOverrides/show_page.scss
app/assets/stylesheets/customOverrides/subheader_users.scss
app/views/catalog/_constraints.html.erb
app/views/catalog/_previous_next_doc.html.erb
app/views/catalog/show.html.erb

Co-Authored-By: Tracy MacMath <tracy.macmath@yale.edu>
**Story**
The addition/update of the "New Search" button in https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1218 seems to have an alignment issue where it bumps "Back to Search Results" below instead of on the same line.  This seems to be happening at full screen, not just at reduced breakpoints.  Update this alignment to keep both buttons aligned side-by-side.
**Acceptance**
https://user-images.githubusercontent.com/41123693/115457853-02247280-a1f3-11eb-92fc-d77a05d98d95.mov

Fixed alignment of "New Search" button

---

app/controllers/application_controller.rb
config/routes.rb
spec/requests/errors_spec.rb

https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1219
- invalid url's from the root endpoint will show the branded 404 page
- invalid endpoints that come after `/catalog` will still show the branded page with the invalid oid
- https://stackoverflow.com/questions/1013152/one-controller-rendering-using-another-controllers-views

1219 return 404 on invalid pages

---

app/views/application/landing.html.erb

Co-Authored-By: Steve Fox <steve@curationexperts.com>
**Story**
From Alison: As you may recall, and as Rebecca knows, the statement on potentially harmful context at the bottom of http://collections.library.yale.edu/ was pending a link to a full statement on the YUL website when we posted it. The text on the YUL website is now in place. Would it be possible to update the statement on http://collections.library.yale.edu/ accordingly?:
**Acceptance**
Yale University Library’s collections contain historical and contemporary materials documenting human expression and lived experience. Content may include images or language that library users may find harmful, offensive, or inappropriate. Some of these words or images are now recognized as offensive and unacceptable; some may have been viewed …

Modified statement on harmful content

---

app/models/concerns/schema_org_solr_document.rb
spec/models/solr_document_spec.rb

Updates schema.org metadata for about property so that it has name and description properties (removes topic and place properties and combines values in description):
e.g.
```
<script type="application/ld+json">
{
"@context": "https://schema.org/",
"@type": "CreativeWork",
"name": [
"The gold pen used by Lincoln to sign the Emancipation Proclamation in the Executive Mansion, Washington, D.C., 1863 Jan 1"
],
"url": "https://collections.library.yale.edu/catalog/2005512",
"genre": [
"Artifacts"
],
"materialExtent": [
"1 pen + 1 case",
"17.5 cm."
],
"temporal": [
"n.d."
],
"thumbnailUrl": "http://localhost:8182/iiif/2/1030368/full/!200,200/0/default.jpg"
}
</script>
```

Update about property of CreativeWork.  Make property values arrays where appropriate.

---

app/controllers/catalog_controller.rb
app/views/catalog/_per_page_widget.html.erb
app/views/catalog/_sort_widget.html.erb
spec/system/advanced_search_spec.rb

**Story**
When completing an advanced search, you then try to toggle from 10 results per page to 20, it seems to execute a search that brings back every item in the collection. It doesn't seem to be a function of how many results a linked search has, as even ones with more than 10 exhibit the same behavior (http://hdl.handle.net/10079/bibid/3660118).
Additionally, this bug occurs with the sort by function on the page
**Acceptance**

1047 advanced search link immutable sort

---

app/helpers/blacklight_helper.rb
app/models/concerns/ogp_solr_document.rb
app/models/solr_document.rb
app/views/catalog/_show_main_content.html.erb
spec/system/show_page_spec.rb

Co-Authored-By: Martin Lovell <martin.lovell@yale.edu>
**Story**
As a user, I'd like links to the site to display properly when pasted into Facebook.   Use OpenGraph to accomplish this: https://ogp.me
**Acceptance**
- Tags are present on an object page
----
Namespace: 
Object page tags:

Added opengraph support

---

app/assets/stylesheets/customOverrides/show_page.scss
app/views/catalog/_show_tools.html.erb

The toolbar alignment on the show page needs rework. 
Acceptance: 
----
Current Design Implementation
----
Desired Design Implementation
----
Actual Design Implementation

Fixed show page toolbar alignment

---

app/controllers/catalog_controller.rb
app/models/concerns/mods_solr_document.rb
spec/requests/catalog_controller_request_spec.rb
spec/support/solr_documents/metadata_cloud_with_visibility.rb

Reindex is required to add languageCode to the solr index.
For Dublin Code, languageCode_ssim is used _**instead**_ of language_ssim.  There doesn't seem to be an easy way to have dublin core first try languageCode_ssim and fall back to language_ssim if languageCode_ssim is not available.
See: https://github.com/projectblacklight/blacklight/blob/master/app/models/concerns/blacklight/document/semantic_fields.rb#L36

1173 add language code to oai mods and change dc language to use code

---

app/assets/stylesheets/customOverrides/show_page.scss
app/views/catalog/_show_tools.html.erb

Acceptance
-----
**Desired Alignment**

Fixed text alignment on the toolbar

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb
spec/system/search_fields_spec.rb

yalelibrary/YUL-DC#1275
*Story**
Searches on Subject appears to return too many results.   I can return results for a match on Call Number using a Subject search:
https://collections.library.yale.edu/catalog?search_field=subjectName_ssim&q=landberg. Results like this one seem only to match the record's Call Number:
**Acceptance**

Fix the use of subject as a search field

---

app/controllers/catalog_controller.rb
app/controllers/concerns/check_authorization.rb
app/controllers/iiif_controller.rb
app/controllers/manifests_controller.rb
app/controllers/pdfs_controller.rb
spec/system/access_restrictions_spec.rb

Ticket: https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1303
This PR implements access control for iiif searches.

1303 access control for iiif search

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/helpers/blacklight_helper_spec.rb
spec/system/highlight_in_search_spec.rb

co-author: alisha evans <alisha@notch8.com>
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1317
- line breaks will be removed from _within_ snippets that have one
- each snippet will have a line break _after_ it
| | |
| --- | --- |
| <img width="1440" alt="image" src="https://user-images.githubusercontent.com/29032869/119726752-4f18eb80-be26-11eb-92ec-c8858cb65856.png"> | <img width="1440" alt="image" src="https://user-images.githubusercontent.com/29032869/119727283-f4cc5a80-be26-11eb-906a-4f9383f0b7cf.png"> |
- lea ann from notch8
- https://apidock.com/rails/ActionView/Helpers/TextHelper/simple_format
- https://stackoverflow.com/a/4190812/8079848
- …

1317 fulltext snippet separation

---

app/helpers/catalog_helper.rb
app/views/catalog/_uv.html.erb
config/uv/uv.html
public/uv/uv.html
spec/system/uv_full_text_search.rb

* UV is configured to accept the search param in its iframe URL via the `q` parameter
* When loading single object show page, retrieves full text search query (if any) from user session and passes it to Universal Viewer iframe.
This initial commit uses the search params stored in the user session, which is not ideal - the state isn't captured in the URL and can't be shared.

Pass fulltext search query to UV when loading show page

---

app/helpers/catalog_helper.rb

Updating field name when passing to UV.
(fulltext_tesim is used as the search field to correspond with the solr field
being searched, as we do with other fields.)

Use fulltext_tesim as search field name when passing params to UV.

---

app/controllers/catalog_controller.rb

**Story**
When searching full text (e.g., "the") in Advanced Search the results highlight matches in other fields (e.g., in the title).
See #1362 for simple search equivalent.
**Acceptance**
----
**Demo of the Feature**

Added exclusive highlighting to advanced fulltext search

---

app/assets/stylesheets/customOverrides/landing.scss
app/views/application/landing.html.erb

**Story**
"I happened to notice yesterday that the link on the homepage of https://collections.library.yale.edu/ still points to the Statement on Harmful Language in Archival Description (https://guides.library.yale.edu/specialcollections/statementondescription), rather than the Statement on Potentially Harmful Content (https://guides.library.yale.edu/about/statement-on-content). I think that’s because I wasn’t clear when we were corresponding back in April that the text (which did change) and also the hyperlink itself should be updated."
**Acceptance**
**Bonus**
-----
**Feature Demo**

Updated harm language statement on landingpage

---

app/models/search_builder.rb

Co-Authored-By: Martin Lovell <martin.lovell@yale.edu>
**Story**
When searching full text (e.g., "the") in Advanced Search the results highlight matches in other fields (e.g., in the title).
See #1362 for simple search equivalent.
**Acceptance**

Modified advance search exclusive highlighting

---

app/helpers/blacklight_helper.rb
app/views/catalog/_show_header.html.erb

**Story**
We switched to breaks instead of "and" in the metadata display, but the page header should also do this:
Object is https://collections.library.yale.edu/catalog/31901015
**Acceptance**
----
**Test Record:**
https://collections-test.library.yale.edu/catalog/800043384
**Current State**
**Proposed State**
----
**Feature Demo**

1367 Separated multiply titles on showpage

---

yarn.lock

**Story**
The application's dependencies should be up-to-date for week 23 of the year. 
**Acceptance:**

1378 Patched blacklight dependancies wk23

---

app/assets/javascripts/application.js
app/assets/stylesheets/customOverrides/search_bar.scss
app/assets/stylesheets/customOverrides/subheader_users.scss
app/controllers/catalog_controller.rb
app/views/catalog/_search_form.html.erb
spec/requests/annotation_request_spec.rb
spec/system/search_fields_spec.rb

**Story**
In FindIt there is descriptive text for the full text search option that displays in a popup when hovering over the "what's this?" text:
In Blacklight we'd like to display a similar message:
```
Search full text that occurs in a work. Not all works contain searchable full text.
```
**Acceptance**
Display the message:

Fulltext simple search

---

app/controllers/catalog_controller.rb
spec/system/view_facet_spec.rb

Story:
We'd like to be able to facet on Collection Title.
Acceptance
Collection Title in the facet:

1419 collection title

---

app/controllers/catalog_controller.rb
spec/system/view_facet_spec.rb

Story:
We'd like users to be able to facet by repository.
Acceptance
Repository in the facet:

add facet repository

---

app/assets/stylesheets/customOverrides/show_page.scss
app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
app/views/catalog/_archival_context.html.erb
app/views/catalog/_show_main_content.html.erb
spec/system/show_page_spec.rb

Show pages will now render the archival context breadcrumbs above the UV:

I1415 archival context

---

app/controllers/catalog_controller.rb
spec/system/highlight_in_search_spec.rb
spec/system/view_fields_in_search_spec.rb

ancestor title display in search result

---

app/assets/stylesheets/customOverrides/show_page.scss
app/views/catalog/_archival_context.html.erb

CSS no longer breaks when the breadcrumbs are more than one line:

1415 css found in text no longer breaks with larger breadcrumbs

---

app/views/application/landing.html.erb

**Story**
The link to the statement on harmful content is in flux.
**Acceptance**
Current Design with Link:
Modified Design with Link:

1464 Removed link from harmful content statement

---

app/views/application/landing.html.erb

**Story**
The link to the statement on harmful content is in flux.
**Acceptance**
Current Link: 
Modified Link:

1464 link modification for harmful content statement

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
app/models/search_builder.rb
spec/helpers/blacklight_helper_spec.rb

Co-authored-by: Martin Lovell <martin.lovell@yale.edu>
Co-authored-by: Martin Lovell <martin.lovell@yale.edu>
**Story**
Updates to Metadata Cloud will potentially return multiple Finding Aid links from Voyager records.
**Blocked by MC ticket 260**
**Acceptance**
See [ticket 1171](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1171)  for more details

1171 Return multiple finding aid and associated links

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

**Story**
If a Finding Aid exists, we'd like to link to it.  Wireframe:
**Acceptance**
TODO: How to handle multiple?
Note/Decision:  We are going to check for collection_title_ssi

1451 display finding aidlink

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

Co-authored-by: Eric DeJesus <eric.dejesus@yale.edu>
**Story**
Users should easily be able to restrict their search to a specific archive or component of an archive.  
**Acceptance**

1485 Added Hierarchy graphical display links to single item page

---

package.json
yarn.lock

Story
The application's dependencies should be up-to-date for week 32 of the year.
---
Acceptance

1498 Blacklight tar Dependency Patching WK32

---

app/assets/stylesheets/customOverrides/show_page.scss

**User Story**
As a user I want the links to be the same color on the whole site. 
Current Design: 
Proposed Design: 
----
**Alternative Description**
The 'found in' links on the result page are not the correct color.

1502 Changed result page 'Found In' links color

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/helpers/blacklight_helper_spec.rb
spec/system/view_fields_in_display_spec.rb

Adds join_as_paragraphs helper for joining an array of strings into &lt;p> tags.
Uses join_as_paragraphs for abstract on show page.

1468 Break abstract up into paragraphs

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

**Story**
Users should easily be able to restrict their search to a specific archive or component of an archive.  
This ticket is the parallel of #1482 but for the top of the individual object page.
**Acceptance**

1483 Add breadcrumbs to hierarchy elements on single object page

---

app/assets/stylesheets/customOverrides/show_page.scss

**User Story**
As a product designer, I want the alignment of the icons and lines pointing to the next icon in the graphical archival tree centered with one another especially when the tree branches are collapsed.  This is under Collection Information on the single object show page.
**Current Design:**
**Proposed Design:**
**Acceptance:**

Modified the graphical archival tree alighnment

---

app/assets/stylesheets/customOverrides/show_page.scss

**Issue**
The advisory about restricted access is not aligned with the rest of the text on the page:
**Acceptance**

Aligned the visiblity messages on single item page

---

app/presenters/yul/metadata_presenter.rb
app/views/catalog/record/_item_metadata.html.erb
spec/rails_helper.rb
spec/system/show_page_spec.rb

**Story**
The Subjects, Formats, And Genres category is sometimes empty.  Ex: https://collections-test.library.yale.edu/catalog/16847708
**Acceptance**

Hide empty metadata blocks from show page

---

app/assets/javascripts/application.js
app/views/catalog/_search_form.html.erb

Remove fulltext option when "description" radio is selected.
Replace and select full text option when "full text' radio is selected.
Use jquery for some dom manipulation.
Determine if fulltext is selected using the parameters rather than localstorage.

1494 remove fulltext option to hide in safari

---

app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

Co-authored-by: Eric DeJesus <eric.dejesus@yale.edu>
**Story**
Currently the hierarchical link tree for archival context under Collection Information on the single object show page shows collapsed with an ellipsis with apparently any more than 2 levels.  This should be updated to go as far as 6 levels before collapsing with ellipsis.  With 7 or more levels, default view should be collapsed to show only the broadest 3 and narrowest 3 with an ellipsis in between; clicking on ellipsis expands to show all levels in the middle.
**Current Design:**
**Proposed Design:**
6 or less:
7 or more:
**Acceptance:**

Changed graphical archival tree expand and collapse breakpoint

---

app/assets/stylesheets/customOverrides/show_page.scss

**Story**
The archival context hierarchy can expand to overlap the section header.  See https://collections-demo.library.yale.edu/catalog/2042376
**Current System Image**
**Modification**
**Acceptance**

1532 archival graphical display expands modification

---

app/helpers/blacklight_helper.rb
app/views/catalog/_constraints.html.erb

**Story**
On page 2 of search results, if I click the breadcrumb to refine my search, I end up on a blank page.   This is because the `page=2` parameter is in the breadcrumb link, but the added restriction returns only one page of results.
The demo cluster has enough objects to test this now.
**Acceptance**
Always send the user to page 1 of the result list when narrowing the search.

Remove page param from archival hierachy links

---

app/assets/stylesheets/customOverrides/show_page.scss
app/controllers/catalog_controller.rb

This design mockup is based on feedback from the Archival Context group, DSU and others. It is meant to address confusion re: the label "Collection Information", and also meant to highlight where the current item is found within the hierarchy. External links are also given more visual separation from the collection info itself. 
**Acceptance:** 
**Don't Include:** 
deactivating the last link in the tree.
**Uploaded here for review before development:**
DEMO:

Created new archival hierarchy design

---

app/controllers/catalog_controller.rb
spec/system/advanced_search_spec.rb
spec/system/archival_sort_spec.rb
spec/system/date_slider_spec.rb

Rework from demo:
- change to ascending not descending order for archivalSort
- add archivalSort to all sort by options
[#1530](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1530)
[#1573](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1573)

Adds archivalSort to all sort bys

---

yarn.lock

User Story
The application's dependencies should be up-to-date for week 36 of the year.
---
Acceptance

Patched Blacklight postcss

---

app/assets/stylesheets/customOverrides/search_result.scss

"Found In" ancestorTitles no longer run off the page on smaller devices.  
Before:  
After:

fixed found in css overlap on small devices

---

app/assets/stylesheets/customOverrides/search_result.scss

Note: This is only a bug on small screens. Added a few more margin-left pixels on small devices.
Before:  
After:

added margin to date field

---

app/views/application/landing.html.erb

**Story**
As a stakeholder, I want the homepage text under the search bar updated to better describe the collections.
The statement ought to read: 
Yale Library's digital collections provide access to millions of digitized works and images. This site is a living database, and new materials are added regularly. Search or click an image below to begin your exploration.
There are Yale Library digital collections not available on this site. More information on these additional collections can be found here.
**Acceptance**
-----
----

Modified digital collection access statement

---

app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

Provides fallback text for when no Collection Title is present.
[#1598](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1598)
On show page it is the `sourceTitle_tesim` that is displayed as 'Collection Title' not the `collection_title_ssi` value that is used for the finding aid link.
- When Collection Title is present
- When Collection Title is not present

Adds finding aid fallback

---

app/assets/stylesheets/customOverrides/show_page.scss
app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

Adds the parent object title as the last element (as text, not a link) of the graphical hierarchy tree on the object show page.
[1601](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1601)

Adds title as final item in graphical hierarchy

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

Multiple rights statements should display on new lines.
[#1613](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1613)

Modifies html sanitize helper

---

app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

Add title to the end of the list, not as a link.
Still show the same number of links.

Add title to the end of the archival hierarchy (found in) on show page

---

app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb
spec/system/view_fields_in_search_spec.rb

Clicking on archival links (found in, breadcrumb, and hierarchy) no longer retains the current search
.

Update archival links to clear current search

---

app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

Changes the display from `collection_title_ssi` to `sourceTitle_tesim` for Collection Title in the finding aid link.
[#1598](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1598)

Changes collection title to source title fallback

---

app/helpers/blacklight_helper.rb
spec/system/show_page_spec.rb
spec/system/view_fields_in_search_spec.rb

The item title is now displayed in the "Found In" hierarchy tree in the search results. Clicking on the title will redirect to the item showpage.

1602 display item in hierarchy search result

---

app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

Adds fallbacks for Collection Title - first `collection_title_ssi`, then `sourceTitle_tesim`, and if neither of those then 'this collection'
[#1598](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1598)

Adds multiple finding aid fallbacks for collection title

---

app/controllers/catalog_controller.rb
spec/system/view_fields_in_search_spec.rb

**Story**
The Voyager volumeEnumeration field ought to display in the search results page list under the object the items with the data. 
**Acceptance**
OR 
Current System View: 
Proposed System View:

1611 Added volume number to search results page

---

app/assets/javascripts/application.js

Calling the resource when full text was not present was returning a 500 Internal server error.  These changes check for the presence of the Full Text button before calling the resource.  Full Text button only displayed when full text is present so this should reduce the number of 500 errors on HoneyBadger.
[#1615](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1615)
https://user-images.githubusercontent.com/36549923/134714312-53c3673c-0494-430c-87d0-aa4881d4633b.mp4
https://user-images.githubusercontent.com/36549923/134714394-0e972ba8-7c19-4092-8e3c-97ae8bed0fb7.mp4

Checks for full text before request

---

app/controllers/catalog_controller.rb
spec/presenters/yul/metadata_presenter_spec.rb
spec/system/view_fields_in_display_spec.rb

Shortens the Container / Volume field label on an item's show page to match the search results page.
[#1641](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1641)

Shortens Container Volume label on show page

---

app/assets/stylesheets/customOverrides/show_page.scss

The archival branch merge removed a CSS style, resulting in an OID displaying beneath the UV.  This restores the style.

Restore CSS for parent-oid

---

app/controllers/catalog_controller.rb
spec/system/view_fields_in_display_spec.rb

Label now read "Container / Volume":

edit volume information label

---

app/controllers/catalog_controller.rb

**Story**
Move the Container/Volume Field to display below archival context tree on an object page. It would appear below context tree but above links to Archives at Yale and the Finding Aid
**Acceptance**
**Actual Image**

Move Container/Volume on object page under hierarchy tree

---

app/controllers/catalog_controller.rb
spec/system/view_fields_in_display_spec.rb

**Story**
We need to display the repository name within the Collection Information section on each object page, for all metadata sources. 
**Acceptance**

Add repository name to object page i1660

---

app/assets/stylesheets/customOverrides/show_page.scss

Brings font size of finding aid and archives at Yale links down to match rest of page.  
[#1662](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1662)

Resizes finding aid links

---

.circleci/config.yml

Co-authored-by: Keith Boyd-Carter <keith.boyd-carter@yale.edu>
Co-authored-by: McClain Looney <mcclain@curationexperts.com>
**Story**
We have a new Solr release (v1.0.8).  CircleCI is referencing a branch build: `image: yalelibraryit/dc-solr:1362_fulltext_suggest_retain_case`
**Acceptance**

Changed circle ci to use the latest solr i1545

---

app/assets/stylesheets/customOverrides/show_page.scss

**Story**
As the product designer, I want less padding around archival context and finding aid links box on the object page.
Actual Design
Propose Design Change
**Acceptance**

Reduce padding around links to Archives at Yale i1676

---

app/assets/stylesheets/customOverrides/landing.scss

As the product designer, I want the alignment of the event boxes to have equal spacing between each image.
Acceptance Criteria
Mobile Image:
Desktop Image:
----
**DEMO**
https://user-images.githubusercontent.com/41123693/136455223-7bb33620-b069-41d1-830d-0117ce3f060b.mov

Aligned events on the landing page

---

config/routes.rb
spec/requests/errors_spec.rb

Fix route for PDF not found page (until we disable the link.)

Fix route for pdf not found page

---

app/controllers/catalog_controller.rb
spec/system/advanced_search_spec.rb

Providing the pf param to solr gave all searches from advanced search the ability to perform complex OR, AND, NOT queries
[#1642](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1642)
https://user-images.githubusercontent.com/36549923/136832594-a2cbfb52-6531-4e22-965b-fd790a8077ae.mp4

Enables complex queries in advanced search

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/system/view_facet_spec.rb
spec/system/view_fields_in_display_spec.rb
spec/system/view_fields_in_search_spec.rb

Adjusts the hierarchy links used in Found In and the archival context tree so that they open the Repository, Collection Name, and Series facets then the links are clicked.

Hierarchy links to facet

---

app/views/catalog/_fulltext_transcription.html.erb
spec/system/show_page_spec.rb

"Show Full Text" button will now display if the object has a "Partial" Fulltext status:  
Object with "Partial" status:

Show Full Text button will now render on 'Partial' fulltext status'

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
app/views/catalog/record/_item_metadata.html.erb
spec/system/view_fields_in_display_spec.rb

**Story**
This ticket is a follow up to #1636. We need to be able to filter the resourceVersionOnline_ssim values currently brought over from Voyager, to exclude:
- Links to the old BRBL DL (in 856:42:$3 - starting http://beinecke.library.yale.edu or http://beinecke1.library.yale.edu)
- Links to YUL's instance of Content DM (in 856:41:$3 starting http://digital.library.yale.edu)
- Divinity's ad hoc server (in 856:42:$3 starting http://divinity-adhoc.library.yale.edu/FosterPapers/)
- Links to Beinecke Library's Digital Images Online database (in 856:41:$3 starting http://brbl-archive.library.yale.edu)
Additionally, all remaining 856 values should map to RelatedResourceOnline not to ResourceVersionOnline
**Acceptance**
----

Added filter for BRBL and other links from ils

---

app/controllers/catalog_controller.rb
spec/support/solr_documents/advanced_search_testing_only.rb
spec/system/date_slider_spec.rb

Deprecated solr fields from management are no longer in Blacklight

Removed deprecated solr fields

---

app/assets/stylesheets/customOverrides/facets.scss

The modal trigger link in the facets should be the same font size and color as the links above it. 
**Current Design**
**Propose Design**
**Acceptance criteria:**
**Actual Design Implementation**

Modified modal trigger link

---

app/models/concerns/ogp_solr_document.rb

Co-Authored-By: Martin Lovell <martin.lovell@yale.edu>
**Story**
Received a report that Facebook is showing the IIIF logo and not the page thumbnail that is provided in the object page's Open Graph metadata.
https://ogp.me
https://collections.library.yale.edu/catalog/11530121
**Acceptance**
Object thumbnail should appear when page link is posted in

Patched image opg metadata

---

app/assets/stylesheets/customOverrides/modal_dialogbox.scss
config/locales/blacklight.en.yml

This is an overview of styling changes that should be made in the "More" modals (facet links)to enhance legibility/readability and improve color contrast. 
Modal Body: 
Modal Footer:
See the mockup below for reference. (Each of these changes can be put into separate tickets if necessary.)
**Proposed Design Image**
**Actual System Image**

Added sytling to more modal

---

app/views/shared/_modal.html.erb

As the product owner, I do not want unnecessary general text in the modal. 
Acceptance Criterion:
Addtional Infomation:
The code had line numbers in it from copy, cut, and dump blacklight project code.  This PR removed the numbers in the codelines for the file.

Removed codeline numbers

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

- Adds Subject Heading link to Show page
- Each part of the subject heading links to the facet.

Add subject heading show field with links to facets

---

app/controllers/catalog_controller.rb
app/helpers/access_helper.rb
spec/requests/manifests_request_spec.rb
spec/requests/pdfs_request_spec.rb
spec/support/solr_documents/metadata_cloud_with_visibility.rb

Allows for redirected parent objects to redirect to their intended destination.
[#1782](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1782)
https://user-images.githubusercontent.com/36549923/148467248-e9826b02-4990-4e8e-883d-da3d2e517c9e.mp4

Implements redirect handling

---

app/assets/stylesheets/customOverrides/show_page.scss
app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
app/models/search_builder.rb
spec/system/highlight_in_search_spec.rb
spec/system/view_fields_in_display_spec.rb

Co-authored-by: Martin Lovell <martin.lovell@yale.edu>
Co-authored-by: Yue Ji <yue.ji@yale.edu>
Co-authored-by: Maggie Zhao <maggie.zhao@yale.edu>
DCS metadata mapping to ArchivesSpace currently pulls in creator information for an object from the collection level of a finding aid, if a creator is not presented at the file/item level. For example, for this parent object https://collections-uat.library.yale.edu/catalog/15603880 the creator listed, is the creator of the collection, listed at the collection level in ArchivesSpace for the collection this item belongs to. This is made obvious on the Archives at Yale record for this item https://archives.yale.edu/repositories/12/archival_objects/802216 which shows that the Creator is "From the collection".
We would like to follow this same …

1845 creator a space mapping

---

app/helpers/access_helper.rb

Removes "Redirect" as a valid visibility for searching, IIIF manifests, PDF documents.
The show page will still redirect correctly because the show page uses a fetch by ID, which isn't affected by the filter query in search builder.

Remove redirect from viewable visibilities array

---

app/controllers/catalog_controller.rb
spec/system/search_fields_spec.rb

Change search_field array's value: ancestor_titles_hierarchy_ssim to ancestorDisplayStrings_tesim in CatalogController. Similar values are in both fields, but the text field is tokenized/stemmed, etc so partial matches will work, etc.

Update search_field so archival hierarchy search works.

---

app/views/shared/_header_navbar.html.erb
spec/system/header_spec.rb

Header Logo now points to https://library.yale.edu/

Updated logo url

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

- Adds the Quicksearch Id field to the identifiers section that links to quicksearch
- Adds quicksearch id to all fields and orbis id search.

Add quicksearch id field

---

app/controllers/catalog_controller.rb
spec/system/sort_in_search_spec.rb

- Adds conditional sort by Collection Order using archivalSort_ssi with the default sort fields as secondary, etc., sorts.
- Checks for Collection facet (collection_title_ssi) and Grouping facet (series_sort_ssi) via CatalogController.collection_order_sort?
- Fixes bug in relevance sort which included `title_si` instead of `title_ssim`

Add conditional sort by Collection Order

---

app/assets/stylesheets/customOverrides/show_page.scss

Container/Volume width now matches the width of the other metadata rows  
[#1838](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1838)

Container/Volume Width

---

config/locales/submenu.en.yml
spec/system/header_spec.rb

The submenu for "Computers Wireless" was renamed to "Computers & Wireless"

Modified a submenu name

---

app/assets/stylesheets/customOverrides/show_page.scss

Co-authored-by: JP Engstrom <jp@notch8.com>
**Story**
We recently deployed a fix for the "Container/Volume" field label, see (#1838). However, this fix appears to have created a new issue, where this field is now misaligned on objects that are associated with ASpace.
See example https://collections.library.yale.edu/catalog/32309327 
Also here is a screenshot for quick reference
**Acceptance**

Modified Container/Volume CSS for ASpace objects

---

app/views/shared/_search_bar.html.erb

**Story**
Users who have searched the DCS would benefit from a way to return to the DCS homepage after conducting a search. A link to https://collections.library.yale.edu/ should be added to the "Digital Collections" text on the left side of the search results page (this is the text above the search limits).
**Acceptance**

Added DCS homepage link to the search result page

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/system/view_fields_in_display_spec.rb

- Allows links in Description field in show page
- Factor out `sanitize_values` for use by `sanitize_first_value` (which just uses the first value and splits at linebreaks and joins with `<br/>`) and  `sanitize_join_with_br` (which joins all values in `<br/>)`
- Renamed `html_safe_converter` to `sanitize_first_value` to make it a clear how it differs from `sanitize_join_with_br`

1970 allow links in desc

---

config/uv/uv.html
public/uv/uv.html

Upon resizing UV from full screen there was a bug that put some controls and parts of the image unavailable to the user.  This PR adjusts the resize function to use UV4 example syntax and restores the UV to the appropriate size and with all options upon exiting full screen.
[#1987](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1987)
https://user-images.githubusercontent.com/36549923/163486204-e2a93669-00f7-4cdc-a028-3a8dc8c20a19.mp4

Enable resize from full screen

---

config/uv/uv.html
public/uv/uv.html

Adds cache meta tags to the uv.html file for UV3
[2041](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2041)

Adds cache meta tags on UV3 uv.html

---

app/helpers/blacklight_helper.rb
spec/helpers/blacklight_helper_spec.rb

Adds alt text to placeholder_restricted image.
[2062](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2062)

Adds alt text to placeholder restricted image

---

config/routes.rb

The iframe link in the share panel in UV4 links to `/uv.html` instead of `/uv/uv.html`.   This is probably because of the embedded flag/not having access to the containing iframe.   This PR adds a redirect so that the iframe works.

Redirect for UV4 iframe link

---

app/controllers/catalog_controller.rb

Changes SOLR query for the children based on parent OID from `q` to `fq`  yalelibrary/YUL-DC#2095

Change parent OID filter to a filter query

---

spec/system/banner_spec.rb

- Update banner link to remove covid banner
- Update banner specs
[#2173](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2173)
These are the result of using the test banner.

Update specs to bypass banner tests

---

app/controllers/catalog_controller.rb
spec/system/view_fields_in_display_spec.rb

Adds digitization funding source to catalog item show page
[#2180](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2180)

Adds digitization funding source to catalog item show page

---

app/helpers/blacklight_helper.rb
spec/helpers/blacklight_helper_spec.rb
spec/system/fulltext_search_spec.rb

Full text search result snippets should only display per the user's access level.
[#2220](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2220)

Suppress Yale Community Only snippets in full text search results

---

spec/system/date_slider_spec.rb

Pulls spec from pending and adjusts the slider increments to get spec to pass again.
[#2225](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2225)
https://user-images.githubusercontent.com/36549923/197869523-67800837-9671-4ac3-a201-a1490bc38727.mp4

Adjusts slide increments

---

app/views/shared/_search_bar.html.erb

Replace hardcoded url to home page with dynamic root path that won't take users out of their environment.
[#2245](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2245)

Change hardcoded url to dynamic path

---

app/views/application/landing.html.erb

Litchfield link changed to `/catalog?f%5Bproject_identifier_tesi%5D%5B%5D=71"`

Fix Litchfield link

---

app/controllers/download_original_controller.rb

In testing on demo the process would not work.  In development this seemed to be due to an uncaught error for NoSuchKey on Aws.  This PR adds error handling for the uncaught error that was previously redirecting to root path.
[#2331](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/gh/yalelibrary/yul-dc/2331)

Add error handling for NoSuchKey

---

Dockerfile
Gemfile

Updates to new base image that includes ruby version 3.1.3.
[#2348](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/gh/yalelibrary/yul-dc/2348)

Updates to base image with ruby 3.1.3

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb

"Partially digitized" and "Completely digitized" now reads "This object has been completely digitized." and "This object has been partially digitized."  
[2335](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/gh/yalelibrary/yul-dc/2335)

updated extent of digitization field value

---

app/controllers/download_original_controller.rb
spec/requests/download_original_spec.rb

Preference to keep the single f file extension desired.  This PR updates the ending to be `.tif`
[#2331](https://github.com/yalelibrary/YUL-DC/issues/2331)

extension ending update

---

app/assets/javascripts/application.js
app/assets/javascripts/download_original.js
app/assets/stylesheets/customOverrides/show_page.scss
app/controllers/download_original_controller.rb
app/views/download_original/tiff_staged.html.erb
config/routes.rb
spec/requests/download_original_spec.rb

Changes redirect to new page that explains the new tab and download process while triggering the download once when the file is available on S3.
[#2416](https://github.com/yalelibrary/YUL-DC/issues/2416)

Changes redirect to new page

---

app/assets/javascripts/download_original.js

Increases the time a download tab will close from 3 seconds to 10 seconds.   
[2443](https://github.com/orgs/yalelibrary/projects/1/views/1?pane=issue&itemId=24187688)

Increase delay time for tab closure

---

app/assets/stylesheets/customOverrides/constraints.scss
app/helpers/blacklight_helper.rb
spec/system/date_slider_spec.rb

Addresses bug that was causing clicking on 'Missing' to send the user to a rails error page.  This PR searches records that are missing their date created field instead of erroring out.
[#2427](https://github.com/yalelibrary/YUL-DC/issues/2427)
https://user-images.githubusercontent.com/36549923/231820183-18e75cd8-c338-4267-ade4-a24ab9ba2791.mp4

Resolves missing bug with date created facet

---

config/honeybadger.yml

Set env to cluster name.  Ignore `local`

Configure Honeybadger to use cluster name as env

---

app/controllers/catalog_controller.rb

.oai_dc_xml path on redirected objects will no longer throw an error.  
To test:  
visit https://collections-test.library.yale.edu/catalog/17451921.oai_dc_xml  
ensure no error is thrown

adds return to redirect

---

app/controllers/catalog_controller.rb

returns nil if oai xml is requested on a redirected object  
Returns not_found page with 404 status if redirected oai_dc_xml url is hit:

returns nil if oai xml is requested on a redirected object

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb

Sierra sources now display correctly as "Morris Record" in Blacklight with the correct URL:

Format morris record url

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb

"Contributor" is now listed in objects Description metadata block.  
"From the Collection:" is present only for ASpace objects:

2543 add contributor field

---

app/views/layouts/blacklight/base.html.erb
spec/user_views_accessible_welcome_page_spec.rb

Adds test to ensure accessibility of Bookmarks page.
[#2566](https://github.com/yalelibrary/YUL-DC/issues/2566)

Make bookmarks page accessible

---

app/views/bookmarks/index.html.erb
app/views/layouts/blacklight/base.html.erb
spec/user_views_accessible_welcome_page_spec.rb

Decreases font tag for Bookmarks tag.
[#2555](https://github.com/yalelibrary/YUL-DC/issues/2555)

Changes font tag

---

app/assets/stylesheets/customOverrides/show_page.scss
public/uv/uv.css

Cyrillic fonts now render correctly in Chrome for UV and breadcrumbs.

UV and breadcrumbs cyrillic font

---

app/assets/stylesheets/customOverrides/search_result.scss

Increased font-weight to 600 since Arial does not include a default bold font. This enables Cyrillic fonts to match non-Cyrillic font weights.

Font-weight for Cyrillic fonts

---

app/helpers/access_helper.rb
spec/helpers/blacklight_helper_spec.rb
spec/requests/annotation_request_spec.rb
spec/requests/download_original_spec.rb
spec/requests/iiif_request_spec.rb
spec/requests/manifests_request_spec.rb

Accessing YCO objects now requires a netid

YCO access now requires a netid

---

app/assets/stylesheets/customOverrides/landing.scss
app/views/application/landing.html.erb

Adds a "Need Help?" section to the landing banner:

(MERGE FIRST) adds help section to landing page

---

app/helpers/blacklight_helper.rb

Extent of Digitization will not show in metadata Description block if value is "unspecified"

hide extent of digitization if value is unspecified

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb

According to the aws logs there was an error with Addressable.  This PR adds the addressable gem in an attempt to resolve the error below.
```
ActionView::Template::Error: uninitialized constant #<Class:0x000055b61f723258>::Addressable
```

Address failing smoke tests

---

app/controllers/catalog_controller.rb

Adds "Provenance" to object showpages:

adds provenance to showpage

---

public/robots.txt

Also include /pdfs/ which should be covered by the section above, but can't hurt.

Block image access for GPTBot in robots.txt

---

app/views/shared/_footer.html.erb

Feedback footer link now works after replacing "&" with "%26"

Feedback Footer Link

---

spec/controllers/omniauth_callbacks_controller_spec.rb

Adds back the tests that were commented out during the cognito implementation.
[#2660](https://github.com/yalelibrary/YUL-DC/issues/2660)

Converts omniauth specs from cas to openid

---

app/assets/stylesheets/customOverrides/index_gallery.scss
app/assets/stylesheets/customOverrides/search_result.scss
app/assets/stylesheets/customOverrides/show_page.scss
app/assets/stylesheets/customOverrides/sort_widget.scss
app/controllers/catalog_controller.rb
app/views/bookmarks/_clear_bookmarks_widget.html.erb
app/views/bookmarks/index.html.erb
app/views/catalog/_index_header.html.erb
app/views/catalog/_show_header.html.erb
app/views/catalog/_show_tools.html.erb
app/views/layouts/blacklight/base.html.erb
app/views/shared/_user_util_links.html.erb
config/locales/blacklight.en.yml
db/schema.rb
spec/factories/users.rb
spec/helpers/blacklight_helper_spec.rb
spec/system/access_restrictions_spec.rb
spec/system/header_spec.rb
spec/user_views_accessible_welcome_page_spec.rb

Adds the bookmark functionality and moves the bookmark check box to the show page header instead of the tools section at the bottom of the page.
[#2663](https://github.com/yalelibrary/YUL-DC/issues/2663)

Adds bookmark functionality

---

app/controllers/catalog_controller.rb
app/helpers/access_helper.rb

Blacklight will fallback to object showpage when missing terms and conditions

Fallback for nil terms

---

Gemfile
Gemfile.lock

Omniauth gem version was upgraded and broke login. This PR reverts the gem to a working version.

Omniauth version

---

app/assets/stylesheets/customOverrides/show_page.scss
app/views/catalog/request_confirmation.html.erb

Prior implementation used a javascript history trick to redirect back to the show page but this change will replace the JS with a standard link_to and will prevent the request loop.
[#2656](https://github.com/yalelibrary/YUL-DC/issues/2656)

Fix continue button link

---

Gemfile
Gemfile.lock

Experiencing log in issues with omniauth gem above version 1.9.2.  This PR pins the gem in place until troublshooting of the issue with newer versions of the gem is determined.

Pin omniauth gem

---

Gemfile.lock
app/assets/stylesheets/customOverrides/index_gallery.scss
app/controllers/catalog_controller.rb
spec/system/search_result_spec.rb

The upgrade work included a update to the blacklight gallery gem.  The update to the gem introduced a [breaking change](https://github.com/projectblacklight/blacklight-gallery/releases/tag/v3.0.1) but the configuration has been updated and now thumbnails and titles are displaying as they were prior to the upgrade work.
[#2755](https://github.com/yalelibrary/YUL-DC/issues/2755)

Update config and styles for gallery view

---

app/assets/stylesheets/customOverrides/show_page.scss
app/controllers/catalog_controller.rb
app/views/catalog/_grouped_metadata.html.erb

Adds the terms and conditions for an open with permission object to the show page, just under the rights statement, with truncation toggle for long text.
[#2745](https://github.com/yalelibrary/YUL-DC/issues/2745)

Add terms and conditions to show page

---

spec/system/fulltext_search_spec.rb
spec/system/show_page_spec.rb

Confirms the behavior that the full text on the search results page will not display if the user does not have permission to view that OwP item and that if the user has permission the field will display.
[#2769](https://github.com/orgs/yalelibrary/projects/1/views/1?pane=issue&itemId=55733595)

Confirm that OwP full text in search results follows access permissions

---

app/helpers/access_helper.rb
app/views/catalog/_show_main_content.html.erb
spec/requests/open_with_permission/owp_object_show_page_request_spec.rb
spec/system/fulltext_search_spec.rb
spec/system/show_page_spec.rb

Original PR was reverted due to search bug in Blacklight. This PR resolves the search bug. OwP items/thumbnails are accessible and visible to Permission Set Admins/Approvers

fixes search bug with owp admin/approver access

---

app/helpers/blacklight_helper.rb
spec/system/fulltext_search_spec.rb

Full Text items being viewed by unauthorized users will see a "Available with permission" next to the Full Text label:  
Without permission:  
With permission:

Full Text label wording 

---

app/views/catalog/_show_main_content.html.erb

Adds a /permission_requests link to the pending request message.

update pending request message

---

app/views/permission_requests/index.html.erb
config/locales/blacklight.en.yml
spec/system/open_with_permission/user_requests_table_page_spec.rb

Removes "Back to Bookmarks" button and updated "Digital Access Requests" to "Access Requests".

Updates to requests page

---

app/assets/stylesheets/customOverrides/landing.scss

On mobile screen the text for the harmful content statement header had too much of a gap.  In adjust this a few other changes were needed to ensure that text would not overlap or be hidden.
[#2584](https://github.com/yalelibrary/YUL-DC/issues/2584)
<details>
</details>

Adjust spacing to prevent text overlap and excessive line height

---

app/assets/stylesheets/customOverrides/search_result.scss

Metadata on mobile will no longer overlap.

increases metadata margin for mobile

---

spec/system/show_page_spec.rb
spec/system/sort_in_search_spec.rb

A few tests are behaving inconsistently in CI so they have been marked as pending because they do pass locally and in CI but the number of reruns it takes to pass is too high.
[#2852](https://github.com/yalelibrary/YUL-DC/issues/2852)
<details>
</details>

Mark flappy specs as pending

---

app/assets/stylesheets/customOverrides/advanced_search.scss
app/assets/stylesheets/customOverrides/search_result.scss
app/assets/stylesheets/helpers/breakpoints.scss

Adds media query breakpoints for xmini mobile devices with 360px screens.  
X-Mini Mobile:  
Advanced Search "All" button:  
Metadata label/value spacing:

adds breakpoint for xmini mobile devices

---

app/assets/stylesheets/customOverrides/show_page.scss
app/assets/stylesheets/customOverrides/subheader_users.scss

Metadata overlapped it's title on Safari browsers 275px wide or less and this PR fixes that issue in Safari along with the overlap of ASpace links and the 'Digital Collections' overlapping the full text search radio button that was occurring in all browsers at 450px and below.
[#2872](https://github.com/yalelibrary/YUL-DC/issues/2872)
<details>
</details>

Fixes overlapping links, metadata, and titles

---

app/controllers/catalog_controller.rb

In testing the object had more metadata which revealed that one of the metadata labels did not have spaces around a `/` and this prevented the label from wrapping on small screens.  This PR adds those spaces to allow wrapping.
[#2872](https://github.com/yalelibrary/YUL-DC/issues/2872)

Adds space so metadata label will wrap on small screens

---

app/controllers/catalog_controller.rb
spec/system/open_with_permission/permission_request_confirmation_page_spec.rb

Previous confirmation page was displaying request form details from prior requests. This PR will display the active request details to the confirmation page

Confirmation Page bug

---

Gemfile
Gemfile.lock
config/webpack/environment.js
package.json
yarn.lock

Webpack and webpack-dev-server needed an upgrade.  This PR includes the upgrades, necessary package additions, and updates to webpack v5 schema configuration.
[#2783](https://github.com/yalelibrary/YUL-DC/issues/2783)

Upgrade gems and packages for webpack

---

app/controllers/download_original_controller.rb
app/controllers/pdfs_controller.rb
app/services/s3_service.rb
spec/requests/pdfs_request_spec.rb

I did some tests by adding a test endpoint to the controller:
`download_original_controller.rb`:
```
before_action :check_authorization, except: [:staged, :test_stream]
...
def test_stream
response.headers['Content-Type'] = 'text/html'
response.headers['ETag'] = '0'
25.times {
puts("SENT ONE")
response.stream.write "<p>#{Time.now}</p>\n"
sleep 1
}
ensure
response.stream.close
end
```
`routes.rb`:
```
get '/download/test_streaming', to: 'download_original#test_stream'
```
I tested by running rails in the container to take nginx out of the picture:
```
rails s -p 9999
```
Then testing it from the container with:
```
curl localhost:9999/download/test_streaming
```
There were two issues:
1. `include ActionController::Live` instead of `include ActionController::Streaming` for this type of …

Add etag to tiff response to prevent rack:ETag from buffering the response

---

app/assets/stylesheets/customOverrides/saved_items.scss

Purpose of ticket 2906 was to update the header on the Saved Items page.  During development additional mismatched font issues were discovered so this PR will also update the Saved Items toggle and button fonts to match the styling of the site.
[#2906](https://github.com/yalelibrary/YUL-DC/issues/2906)
<details>
</details>

Adjust Saved Items Styles

---

app/assets/stylesheets/customOverrides/permission_request_form.scss
app/assets/stylesheets/customOverrides/show_page.scss
app/views/catalog/request_confirmation.html.erb
app/views/catalog/request_form.html.erb
spec/requests/open_with_permission/owp_object_show_page_request_spec.rb
spec/system/open_with_permission/permission_request_confirmation_page_spec.rb

New form styles for OwP Confirmation and Request forms.  
Request Form:  
Confirmation Page:

OwP Request/Confirmation Styling

---

app/controllers/catalog_controller.rb
app/controllers/permission_requests_controller.rb
app/helpers/access_helper.rb

Blacklight will not expect the owp auth header back from management and in case no permission requests are found this PR also adds another guard for this.
[#2877](https://github.com/yalelibrary/YUL-DC/issues/2877)

Updates logic for unauthorized OwP request

---

app/assets/stylesheets/customOverrides/permission_requests.scss
app/views/permission_requests/index.html.erb

The Access Until column was not sorting chronologically.  This PR adjusts the sorting to use date based sorting.  This also adjusts the double arrow to no longer be cut off in some media screen sizes.
[#2921](https://github.com/yalelibrary/YUL-DC/issues/2921)

Adjusts table sorting

---

app/helpers/access_helper.rb
spec/factories/users.rb
spec/requests/annotation_request_spec.rb
spec/requests/download_original_spec.rb
spec/requests/iiif_request_spec.rb
spec/requests/manifests_request_spec.rb
spec/requests/open_with_permission/create_permission_requests_request_spec.rb
spec/requests/open_with_permission/owp_object_show_page_request_spec.rb
spec/requests/pdfs_request_spec.rb
spec/system/fulltext_search_spec.rb
spec/system/open_with_permission/owp_agreement_term_spec.rb
spec/system/open_with_permission/permission_request_confirmation_page_spec.rb
spec/system/open_with_permission/user_requests_table_page_spec.rb
spec/system/show_page_spec.rb

Ensures there is test coverage of restricted urls for authenticated yale and non yale, off campus, and unauthenticated users.
Also, updates a call to management to use a user's uid not netid for retrieving permissions - as management is expecting here - `yul-dc-management/app/controllers/api/permission_sets_controller.rb:42`.
[#2919](https://github.com/yalelibrary/YUL-DC/issues/2919)

Expands tests for various users

---

app/helpers/access_helper.rb
spec/requests/download_original_spec.rb
spec/requests/open_with_permission/owp_object_show_page_request_spec.rb
spec/requests/pdfs_request_spec.rb
spec/system/fulltext_search_spec.rb
spec/system/show_page_spec.rb

Fixes switch from netid to uid back to netid.  Only yale users will have netids and non yale users will not have permissions to manage owp works.

Only yale users have netids

---

ops/webapp.conf

This PR will disable the daily security check Passenger performs when loading.  
[#2930](https://github.com/yalelibrary/YUL-DC/issues/2930)

Disable daily security check for Passenger

---

app/assets/stylesheets/customOverrides/landing.scss
app/views/application/landing.html.erb
app/views/shared/_landing_flash_msg.html.erb
config/locales/devise.en.yml

Success auth message now displays, "Successfully logged in."  
Also removed the blank white bar under the flash message.

Auth Message

---

app/assets/stylesheets/customOverrides/show_page.scss

Aligns metadata with the UV. The metadata will scale down automatically in line with the UV.  
Regular 100%:  
Zoomed out 67%:  
Smaller screen:

align metadata

---

app/controllers/download_original_controller.rb
spec/requests/download_original_spec.rb

Enables our standard auth for staged downloads.  
Users receive an 'unauthorized' message if attempting to download tiff via direct url

Staged Download auth

---

config/initializers/content_security_policy.rb

CSP kept the styles from working on the object show page.  This expands the policy to allow the style attribute to function.
[#2875](https://github.com/yalelibrary/YUL-DC/issues/2875)

Allow style attribute

---

app/controllers/mirador_controller.rb
app/views/application/landing.html.erb
app/views/catalog/_grouped_metadata.html.erb
app/views/catalog/_schema_org_metadata.html.erb
app/views/catalog/_uv.html.erb
app/views/mirador/show.html.erb
app/views/permission_requests/index.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_ga_header.html.erb
config/initializers/content_security_policy.rb

Remove some of the broad rules from general content security policy and add customized CSP for controllers that require exceptions to operate successfully.
[#2977](https://github.com/yalelibrary/YUL-DC/issues/2977)

Add Customized CSP

---

app/helpers/blacklight_helper.rb
spec/system/show_page_spec.rb

Clicking a special character Creator link on a showpage will now search correctly and return the correct results.

Creator search link

---

app/assets/stylesheets/customOverrides/saved_items.scss

Removes font-family from bookmark dropdown.

Bookmark Dropdown Font

---

app/assets/stylesheets/customOverrides/search_result.scss

Bootstrap 5 upgrade included adding padding to rows.  This addresses the misalignment of the title section and fixes overlap on mobile view of 'Save Item' checkbox.
<details>
</details>

Fixes misalignment of title

---

app/assets/stylesheets/customOverrides/index_gallery.scss
app/assets/stylesheets/customOverrides/search_result.scss

Absolute position for bookmark toggle moved the item off the visible screen for the user after the bootstrap upgrade.  This changes the toggle's positioning for visibility at all screen sizes.
<details>
</details>

Reposition bookmark toggle

---

app/assets/stylesheets/customOverrides/constraints.scss
app/assets/stylesheets/customOverrides/pagination.scss
app/assets/stylesheets/customOverrides/search_result.scss
app/assets/stylesheets/customOverrides/show_page.scss
app/components/yul/system/modal_component.html.erb
app/views/catalog/_citation.html.erb

Fixes alignment of New Search links, citation modal not closing, and hover underline of metadata links.
<details>
</details>

Styles links

---

app/assets/javascripts/application.js
app/assets/javascripts/blacklight_date_range.js
app/assets/javascripts/notifications.js
app/assets/stylesheets/customOverrides/advanced_search.scss
app/assets/stylesheets/customOverrides/constraints.scss
app/assets/stylesheets/customOverrides/facets.scss
app/assets/stylesheets/customOverrides/footer.scss
app/assets/stylesheets/customOverrides/notifications.scss
app/assets/stylesheets/customOverrides/show_page.scss
app/assets/stylesheets/customOverrides/subheader_users.scss
config/uv/uv.html

Additional Bootstrap upgrade styling fixes:
* no more duplicate 'Full Image (jpg)' Download option
* citation modal close button aligned to right side
* facet modal remove link underlines and align buttons
* footer remove underline for not active links
* advanced search tips are beside inputs on large screens, not below
* no more underlines on facet links or Digital Collections main link - except on hover/active/focus
* 'apply' button for date range filter is visible in facet and in modal
* search term results are left aligned
* close 'X' on notification messages is right aligned
<details>
</details>

Resolve spacing issues

---

config/uv/uv.html

Solving the duplicate full jpg image download option hid the top navigation for the UV panel as well.  This restores the UV navigation as well as the duplicate option - which will be addressed in ticket [#3034](https://github.com/yalelibrary/YUL-DC/issues/3034).
[#3035](https://github.com/yalelibrary/YUL-DC/issues/3035)

Restore UV top navigation options

---

app/assets/stylesheets/customOverrides/pagination.scss

Bootstrap 5 assigned a negative gutter that hid the borders on the pagination design.  The addition of the margin left override restores consistent line weight for pagination options.

Fix conflicting styles for pagination

---

config/uv/uv-config.json
config/uv/uv.html

Restores some styling of the download dialogue box for UV to pre - bootstrap upgrade styles.
[#3034](https://github.com/yalelibrary/YUL-DC/issues/3034)

Remove duplicate option and add line breaks to UV download dialogue

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
spec/system/show_page_spec.rb
spec/system/view_fields_in_display_spec.rb

Updates label to 'Catalog Record' for all objects and uses mms_id as identifier for Alma records.
[#3022](https://github.com/yalelibrary/YUL-DC/issues/3022)

Update Catalog Links

---

package.json
yarn.lock

Objects with 'paged' behavior were not automatically loading in the Two Up View.  Upgrading UniversalViewer includes fix - [commit `cab1e47`](https://github.com/FalveyLibraryTechnology/universalviewer/commit/cab1e474e22edfcb88d6ad927c8c9f8270f01ec8) - that makes checking for paged behavior more explicit and resolves the default loading issue.
[#3060](https://github.com/yalelibrary/YUL-DC/issues/)

Upgrades UV to v4.2.0-rc4

---

app/assets/stylesheets/customOverrides/show_page.scss
app/views/catalog/_uv.html.erb

Overlay for an object with Sensitive materials can now be toggled via "Hide Object" button

adds toggle to hide sensitive materials object

---

.circleci/config.yml

Removes deprecation warning in CircleCI for outdated deploy syntax by upgrading the docker orb.
[#3164](https://github.com/yalelibrary/YUL-DC/issues/3164)

Upgrade docker orb

---

app/assets/stylesheets/customOverrides/landing.scss

Makes sure that the advanced search link does not return to default colors for links and remains visible on all screen sizes.
[#3166](https://github.com/yalelibrary/YUL-DC/issues/3166)

Changes text color of advanced search link on small screens
