Gemfile
Having the Gemfile alphabetized makes it easier to manage.
=> Alphabetize Gemfile

README.md
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/79
As a team member, I’d like some guidance about how to set up a dockerized development environment, so that I can start helping to work on the blacklight application quickly and easily.
- Instructions for how to start the blacklight app with Docker
- Instructions for how to enter the web container
- Instructions for how to use the console/debug through Docker
=> i79-docker-dev-readme-update

.env, Dockerfile, docker-compose.yml
This PR:
- changes image org/name
- removes additional docker-compose stuff
- renames services for clarity (images and manifests)
=> Change DockerHub Locations

README.md
- remove outdated section
- better document indexing the sample data
=> readme-updates-v2

app/views/shared/_footer.html.erb, config/initializers/git_sha.rb
* Partially resolves Ticket #113 Add version/sha footer to blacklight app
* Additional information needed to close out deployment information tag
=> add version info footer

.dockerignore, app/views/shared/_footer.html.erb, config/initializers/git_sha.rb
* Relates to Ticket #113 - add version footer w/ sha, branch, and deployment information
* Removes .git from dockerignore 
* Updates text in footer 
* Will need to be evaluated in deployed environment
=> Unignore git

.circleci/config.yml, README.md
* All PRs build and push an image to dockerhub
* All PRs run tests against that newly built image
* PRs merged to master also build and tag and push a `:master` tag to dockerhub
=> Build and push image each time

Dockerfile, Dockerfile.base
Co-authored by [Bess Sadler](bess@curationexperts.com) and [Frederick Rodriguez](frederick.rodriguez@yale.edu)
Moved the Chrome install into the Dockerfile and pushed up new dockerhub images
=> move-chrome-to-base

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/helpers/blacklight_helper.rb, spec/helpers/blacklight_helper_spec.rb, spec/system/view_facet_spec.rb, spec/system/view_fields_in_display_spec.rb, spec/system/view_fields_in_search_spec.rb
See https://github.com/yalelibrary/YUL-DC/issues/158
=> Display language codes in English

Dockerfile, Gemfile, app/controllers/catalog_controller.rb, docker-compose.yml, spec/system/view_facet_spec.rb
Also, increment base build and ruby minor version
=> Remove pivot field from facets

.env, .gitignore, Dockerfile, Gemfile, README.md, docker-compose.yml
Blacklight is going to get its data from the management application, so we need to start using it to generate our data.
* Add the management app to docker-compose
* Update environment variables to match other Yale microservices applications
* Remove redundant environment variables from .env
=> Integrate management app for data indexing

README.md
ReadMe updates for starting the container and indexing data
=>  readme-fix

app/controllers/catalog_controller.rb, spec/system/view_fields_in_display_spec.rb
pull the code and test
The Genre facet should appear on the left side:
=> adds Genre Facet

Dockerfile.base, docker-compose.yml
Also Pin base layer of Dockerfile to a specific release
Connected to https://github.com/yalelibrary/YUL-DC/issues/200
Connected to https://github.com/yalelibrary/YUL-DC/issues/201
=> Collapse chrome installation into a single docker layer

.github_changelog_generator, CHANGELOG.md, Gemfile, Gemfile.lock, README.md
Keeping a change log is a software development best practice. See https://keepachangelog.com/en/1.0.0/ for more explanation. This PR introduces a process for auto-generating a changelog for this project. The notes from the change log can also be used as release notes for our releases.
=> Autogenerate changelog and release notes

.rubocop_todo.yml, app/controllers/catalog_controller.rb, app/helpers/blacklight_helper.rb, spec/system/view_fields_in_display_spec.rb
Pull the code and test the language link on the show page.
=> Add a link for Language on the show page

.github_changelog_generator, CHANGELOG.md, README.md
* Generate changelog
* Update README to document release process
=> Prep for v1.2.2 release

app/controllers/catalog_controller.rb, spec/system/view_fields_in_display_spec.rb
Reverts yalelibrary/yul-dc-blacklight#107
=> Revert "Use a different date Solr field"

app/controllers/catalog_controller.rb, spec/system/view_fields_in_display_spec.rb
- pull code into the test environment 
- the change is to the date field (see image)
=> Remove DataStructure field and replaced with Date field

.circleci/config.yml
Part of https://github.com/yalelibrary/YUL-DC/issues/250
=> Only bundle when we have to so that CI is fast again

Gemfile, Gemfile.lock
See https://app.honeybadger.io/onboarding/install for additional details.
=> Add Honeybadger for execption reporting in production

.rubocop_todo.yml, app/controllers/catalog_controller.rb, spec/system/sort_in_search_spec.rb
Connected to https://github.com/yalelibrary/YUL-DC/issues/242
Ticket: https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/242
=> Sort search results by date from newest to oldest and oldest to newest

.circleci/config.yml, config/blacklight.yml
Connected to https://github.com/yalelibrary/YUL-DC/issues/232
=> Segregate automated tests to use their own solr index

README.md
Connected to https://github.com/yalelibrary/YUL-DC/issues/269
=> Update readme with test coverage info

app/lib/yale/citation_string_processor.rb, spec/helpers/citation_helper_spec.rb
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/293
- The code coverage for citation_string_processor.rb has increased from 83.78% to 96.97%
=> Increase code coverage for citation_string_processor.rb

config/honeybadger.yml
Set honeybadger to use named HONEYBADGER_API_KEY_BLACKLIGHT variable
=> Set honeybadger key using env var

app/assets/config/manifest.js, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/blacklight.scss, app/assets/stylesheets/customOverrides/footer.scss, app/assets/stylesheets/customOverrides/header.scss, app/assets/stylesheets/customOverrides/search_result.scss
- technical improvement
- created a better structure so we don't have to import our files into every file
- moved a style property that was in the now deleted "blacklight.scss" file
- https://gitlab.com/notch8/essi/-/tree/master/app/assets/stylesheets
- https://github.com/projectblacklight/blacklight/wiki/Theming
just to show that nothing changed as far as the user sees
=> Update the app's styling architecture

app/assets/stylesheets/customOverrides/header.scss, app/assets/stylesheets/theme/colors.scss, app/controllers/catalog_controller.rb, app/views/application/_ask_library.html.erb, app/views/application/_reserve_rooms.html.erb, app/views/application/_study_places.html.erb, app/views/shared/_user_util_links.html.erb, config/locales/blacklight.en.yml, spec/system/header_spec.rb, spec/system/user_authentication_spec.rb
=> Add links to nav bar including style

.circleci/config.yml
Connected to https://github.com/yalelibrary/YUL-DC/issues/372
=> Sanitize branch name in CI

Gemfile, Gemfile.lock, config/application.rb, config/environments/development.rb, config/environments/production.rb
* rails_semantic_logger gem added & configured
* logs to stdout, file appenders removed
* semantic conversion suppressed in dev
* amazing_print added to dev mode (for colorized logs)
=> Add support for semantic logging

app/controllers/omniauth_callbacks_controller.rb, app/models/user.rb, app/views/shared/_user_util_links.html.erb, config/routes.rb, public/uv/uv.html, spec/controllers/omniauth_callbacks_controller_spec.rb, spec/factories/users.rb, spec/system/user_authentication_spec.rb
@bess has a bit a thing with the specs. in test mode it ignores there host part of the redirect somehow? I can't figure out how. I tried webmock but because its local it never hits the mock. Either way, this tests that it sees the right omniauth url now, not that the omniauth url goes to the right place.
=> Sign into cas

app/assets/stylesheets/customOverrides/footer.scss, app/assets/stylesheets/customOverrides/header.scss
Locally running in production mode the logo was not showing. Making this change it then does show.
=> Use image-url so that asset pipeline works properly

docker-compose.yml
Co-authored-by: Rob Kaufman <rob@notch8.com>
Change files for the management application to work at the startup of the blacklight application.
=> Management with direct app start

README.md
Connected to https://github.com/yalelibrary/YUL-DC/issues/417
=> Add moving tickets to release process

app/controllers/catalog_controller.rb, spec/system/view_facet_spec.rb
Add facets and reorder according to list below
*    Extent of Digitization
*    Format
*    Genre
*    Resource Type
*    Language
*    Author
*    Subject Topic 
*    Subject Name 
*    Call Number
*    Digital Collection
*    Publication Date
#426
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/426
=> Reorder and add facets

app/assets/stylesheets/customOverrides/footer.scss, app/assets/stylesheets/customOverrides/header.scss, app/assets/stylesheets/customOverrides/main.scss
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/466
- All page content, except for the search bar, is even left and right aligned
- The white space on the left and right of the page has been reduced
=> Remove left and right page margin

Gemfile, Gemfile.lock, ops/nginx.sh
Moved the `gem 'rails-controller-testing'` in to the test group to fix the exceptions on app code changes.
=> Upgrade Blacklight to 7.10.0 and fix dev mode reload issue

app/assets/stylesheets/customOverrides/search_result.scss, app/assets/stylesheets/customOverrides/show_page.scss, app/views/catalog/_show_header.html.erb, spec/helpers/citation_helper_spec.rb, spec/system/view_fields_in_display_spec.rb
---
**UV Page Design**
---
https://share.getcloudapp.com/6queJe0z
=> Single item uv styling

.rubocop_todo.yml, app/assets/stylesheets/customOverrides/pagination.scss, app/assets/stylesheets/customOverrides/show_page.scss, app/controllers/concerns/blacklight/search_context.rb, app/views/catalog/_index_header.html.erb, app/views/catalog/_previous_next_doc.html.erb, app/views/catalog/_show_main_content.html.erb, app/views/catalog/_start_over.html.erb, app/views/catalog/show.html.erb, spec/system/show_page_spec.rb, spec/system/single_item_pagination_spec.rb
=> Style single page pagination using Yale branding

app/views/catalog/_home_text.html.erb
**ACCEPTANCE**
Welcome!
Welcome to the Yale University Digital Collections internal preview site
The initial preview includes approximately 500 publicly accessible items from across the Beinecke's digital holdings
At launch, the Digital Collections Platform will contain over 125,000 items representing the Beinecke Library’s digital holdings
In addition, the site will include content belonging to one additional collection from another Yale University Library repository at the initial public launch
Future phases will incorporate additional content from across YUL's digital holdings
Please feel free to explore the site and share your feedback with us.
The preview is designed to give a fully functional preview of browse, search, and view capabilities as we migrate content from the legacy …
=> Modified text on welcome page

app/controllers/saved_searches_controller.rb, app/controllers/search_history_controller.rb, app/views/advanced/_advanced_search_form.html.erb
**Bug Report:**
The application encountered the following error: uninitialized constant Blacklight::SavedSearches
output: /home/app/webapp/app/controllers/saved_searches_controller.rb:2:in
**Action** 
Deletion of files: 
- saved_searches_controller
- search_history_controller
**Other Action(s)**
Modification to remove the date facet in app/views/advanced/_advanced_search_form.html.erb.
=> Fix bug for deployment of code v1.16.0

app/assets/stylesheets/customOverrides/facets.scss, spec/system/view_facet_spec.rb
Further styling for facet sidebar
#462 (ZenHub Link)[https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/462]
=> Add styling for facets

app/assets/stylesheets/customOverrides/index_gallery.scss, app/assets/stylesheets/customOverrides/search_bar.scss, app/views/catalog/_index_gallery.html.erb, spec/system/search_result_spec.rb
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/471
- the gallery is 1 column wide on screens 320px - 566px wide
- the gallery is 2 columns wide on screens 567px - 1159px wide
- the gallery is 3 columns wide on screens 1200px and larger
=> Style gallery view search results

app/helpers/blacklight_helper.rb, spec/helpers/blacklight_helper_spec.rb
Connected to https://github.com/yalelibrary/YUL-DC/issues/558
=> Treat unreachable thumbnail urls like absent images

README.md
- the deployment process for https://collections-demo.curationexperts.com/ and https://collections-test.curationexperts.com/ have been updated
=> README deployment steps update

Gemfile, Gemfile.lock
=> Upgrade actionview to address security issue

Dockerfile
Connected to https://github.com/yalelibrary/YUL-DC/issues/551
=> Updgrade to new base image

app/views/catalog/record/_keyword_metadata.html.erb
Change metadata group title from 'Keyword' to 'Keywords'
=> Edits metadata group title

app/assets/stylesheets/customOverrides/show_page.scss, app/controllers/catalog_controller.rb, app/models/solr_document.rb, app/views/catalog/_show_links.html.erb, spec/system/show_page_spec.rb
Remove email and sms this, move manifest link into tools
Remove links section since it will be empty
=> Delete sms and email from tools on show page

.rubocop.yml, app/assets/stylesheets/customOverrides/show_page.scss, app/controllers/catalog_controller.rb, spec/system/date_slider_spec.rb
Allows for searching by limiting the date range only
https://share.getcloudapp.com/YEuoxork
=> Reorders inclusion of date slider gem

app/assets/stylesheets/customOverrides/advanced_search.scss, spec/system/advanced_search_spec.rb
**Current Design:** 
**Intended Design:**
=> Style advanced search button

app/assets/stylesheets/customOverrides/header.scss, app/assets/stylesheets/customOverrides/sort_widget.scss, app/views/shared/_header_navbar.html.erb
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/564
- Clicking the "sort by..." drop down expands vertically
- Clicking the "... per page" drop down expands vertically
=> Fix the search result drop downs

app/views/shared/_header_navbar.html.erb
removed a leftover console log
=> Remove leftover console log

app/views/catalog/_home_text.html.erb
Tell users where to look for the BugHerd icon
=> Update welcome text

app/assets/stylesheets/customOverrides/show_page.scss, app/views/catalog/record/_description_metadata.html.erb, app/views/catalog/record/_identifier_metadata.html.erb, app/views/catalog/record/_keyword_metadata.html.erb, app/views/catalog/record/_migration_source_metadata.html.erb, app/views/catalog/record/_origin_metadata.html.erb, app/views/catalog/record/_usage_metadata.html.erb, spec/system/view_fields_in_display_spec.rb
Styles the single item page body
#477 [ZenHub](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/477)
=> Adds styling to single item page body

.env
While troubleshooting with Rachel K and Maura, we found that our .env file has some variables that are no longer needed
=> Removed outdated env variables

app/assets/stylesheets/customOverrides/advanced_search.scss
Current UI: ![Screen Shot 2020-10-02 at 1.39.05 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/091b3682-a522-4249-9ac3-561e0a2ad4cf)
Expected UI: ![Screen Shot 2020-10-02 at 1.39.17 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/7134d94a-fcd8-4a0e-8537-461c325efe3a)
=> Fix missing list view button

app/controllers/catalog_controller.rb
This removes autocomplete from the search box.
It should also resolve issue 633 - Short Search Bar
=> Removes autocomplete

app/controllers/catalog_controller.rb
Removes Did you Mean from the UI.
=> Disables spell check 'Did you mean'

.circleci/config.yml, Dockerfile, README.md
Bumps Camerata base image version to 1.1.0
=> Update base image version

app/views/catalog/_show_links.html.erb, app/views/shared/_footer.html.erb
There were a few typos in the html.
(If we are really lucky, this might help with edge/IE rendering.)
=> Fixes html tag bugs

app/assets/stylesheets/customOverrides/main.scss, app/assets/stylesheets/customOverrides/search_bar.scss, app/views/advanced/index.html.erb, app/views/shared/_header_navbar.html.erb
This will make styling on other areas of the screen easier.
=> Targets css more specifically

app/assets/stylesheets/customOverrides/facets.scss, spec/system/date_slider_spec.rb
Co-authored-by: Maggie Zhao <maggie.zhao@yale.edu>
Co-authored-by: Maura Carbone <maura.carbone@yale.edu>
**ACCEPTANCE**
=> Style dateslider

app/controllers/catalog_controller.rb
**Currently the solr field lc_1letter_ssim is not being used for Call Number inside the code:**
This is code cleanup.
=> Remove un-used code

app/assets/stylesheets/customOverrides/show_page.scss
Co-authored by: Martin Lovell<martin.lovell@yale.edu>
=> Change padding to margin for manifest class so cite link will show.

app/helpers/blacklight_helper.rb, spec/system/metadata_line_breaks_spec.rb
=> Separates subject, name, and geo topics with line break on show page

app/controllers/catalog_controller.rb, app/helpers/blacklight_helper.rb, app/views/catalog/_constraints.html.erb, app/views/catalog/_constraints_element.html.erb, spec/support/capybara.rb, spec/system/date_slider_spec.rb
Reverts yalelibrary/yul-dc-blacklight#357
=> Revert "Fix date slider bounds and tests. Add date constraint."

app/views/catalog/_constraints_element.html.erb
Accessibility change, see yalelibrary/YUL-DC#820
=> Remove redundant title attribute on constraints

app/models/user.rb, config/initializers/devise.rb, spec/system/user_authentication_spec.rb
Set user session timeout to 12 hours
=> Set user session timeout to 12 hours

ops/webapp.conf
Log x-forwarded-for header to nginx access log
=> Enable x-forwared-for

app/assets/stylesheets/customOverrides/advanced_search.scss, app/assets/stylesheets/customOverrides/search_bar.scss, app/assets/stylesheets/customOverrides/show_page.scss
Fixes hover to be consistent with bolder outline, fixes color inconsistency, and fixes 'focus' text color for main search bar
=> 798 button hover

app/helpers/advanced_helper.rb, app/views/advanced/_advanced_search_fields.html.erb, app/views/advanced/_advanced_search_form.html.erb
=> Adds Aria Described by to advanced search fields

app/controllers/catalog_controller.rb
Connected to https://github.com/yalelibrary/YUL-DC/issues/777
=> Ensure all facets being displayed show "more" if they return > 10 result

app/views/shared/_footer.html.erb, app/views/shared/_header_navbar.html.erb, app/views/shared/_user_subheader.html.erb
Connected to https://github.com/yalelibrary/YUL-DC/issues/816
=> Ensure top level sections have aria roles and labels

ops/webapp.conf
Fixed original PR by moving log_format outside of the server block.
=> Enable x forwared for

app/views/catalog/_show_tools.html.erb
Connected to https://github.com/yalelibrary/YUL-DC/issues/824
=> Make image part of link for accessibility

app/assets/stylesheets/customOverrides/pagination.scss
Connected to https://github.com/yalelibrary/YUL-DC/issues/822
=> Larger targets for pages

app/views/advanced/index.html.erb
=> added h1 to Advanced Search

app/assets/stylesheets/customOverrides/advanced_search.scss, app/assets/stylesheets/customOverrides/constraints.scss, app/assets/stylesheets/customOverrides/main.scss, app/assets/stylesheets/customOverrides/search_bar.scss, app/assets/stylesheets/customOverrides/show_page.scss
Want someone to review my choices and have one question about a button function
=> Fix advanced search in search bar vanish issue

app/assets/stylesheets/customOverrides/constraints.scss
**DETAILS**
See issue 4 in https://drive.google.com/open?id=1KsZmdBi00ScskmAMffnM1O_N-CnMUZIv
**ACCEPTANCE**
=> Add more height to the filter button

app/assets/stylesheets/theme/typography.scss
Chrome and FF were not actually displaying Mallory, had woff2 files added to site and updated typography files, is working on local
=> Fix fonts mallory

Dockerfile
Upgrades to base version that uses postgres 12
=> Upgrade base

README.md
https://github.com/yalelibrary/yul-dc-camerata/pull/273 will need to be approved before this PR is approved!
- points the release and deploy steps towards the camerata repo
=> Move release/deploy steps to the camerata repo

app/controllers/iiif_controller.rb, config/routes.rb, ops/nginx.sh, ops/webapp.conf, spec/requests/iiif_request_spec.rb
this time use the auth module from nginx (thanks Mike!) https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/
=> Working on getting IIIF Auth Working in Prod

app/views/shared/_header_navbar.html.erb
The user menu in the blacklight app has an inconsistent mouse behavior.  The mouse pointer displays a cursor when hovered on the text and a pointer when hovered on the arrow.
=> Update drop down arrow cursor on the user submenu

app/views/catalog/_search_form.html.erb, spec/system/advanced_search_spec.rb
Connected to https://github.com/yalelibrary/YUL-DC/issues/690
=> Advanced search should be fresh search context

Gemfile, Gemfile.lock, app/assets/stylesheets/customOverrides/header.scss, app/views/shared/_user_util_links.html.erb, spec/system/user_authentication_spec.rb
Addresses Omniauth CVE-2015-9284  
Per yalelibrary/yul-dc#836 follows example of management app.
=> Change login links to buttons for Omniauth

app/views/catalog/_home_text.html.erb
Updates the message displayed on the /catalog page when no search is submitted
=> Updates the message displayed on the /catalog page

app/assets/javascripts/application.js, app/assets/stylesheets/customOverrides/constraints.scss, app/assets/stylesheets/customOverrides/landing.scss, app/assets/stylesheets/customOverrides/main.scss, app/assets/stylesheets/customOverrides/search_bar.scss, app/views/advanced/_advanced_search_form.html.erb, app/views/catalog/_constraints_element.html.erb, app/views/catalog/_search_form.html.erb, app/views/catalog/_start_over.html.erb, app/views/catalog/show.html.erb, spec/system/advanced_search_spec.rb, spec/system/show_page_spec.rb
Update some links to be buttons.
Some buttons containing links will now work when clicking space bar on the button.
Update some styling for pseudo classes that had contrast issues.
Co-authored-by: Maura Carbone <maura.carbone@yale.edu>
=> 874 button access 2

app/assets/stylesheets/customOverrides/landing.scss, app/views/application/landing.html.erb
Updates homepage per Tricia C.
Changes "Coming soon..." to "More coming soon..." and remove link.
=> Update landing page text and remove coming soon link

app/assets/stylesheets/customOverrides/landing.scss, app/views/application/landing.html.erb
Still needs a final link so this is just a draft
=> Add content statement to bottom of landing page

app/controllers/catalog_controller.rb
Made a few easy fixes that were in bugherd re: the UI
- source title is now collection title
- collection title appears always in the search results screen
- extent has line breaks
- description has line breaks
=> Bugherd Fixes

app/views/application/landing.html.erb, app/views/layouts/blacklight/base.html.erb, app/views/mirador/show.html.erb, app/views/shared/_ga_body.html.erb, app/views/shared/_ga_header.html.erb
On the main page, click 'View source' and you should see under <head> the following:
Under <body class="blacklight-catalog blacklight-catalog-show"> you should see:
Do the same for the following pages:
Search Results
Single Item
Mirador Viewer
=> Google Analytics addition

app/controllers/catalog_controller.rb, spec/support/solr_documents/all_fields_record.rb, spec/system/view_fields_in_display_spec.rb
=> Add sourceCreator_tesim to display

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/models/solr_document.rb, config/routes.rb
So far - add oai provider gem, run installer
=> Add OAI Mods Support

spec/system/sitemap_show_spec.rb
Change the wording on a test to accurately describe the condition.
=> Modified test description for better narrative

package.json, yarn.lock
=> Recommended git security update

app/assets/javascripts/application.js, spec/system/banner_spec.rb
=> 1210 Update banner JS code to replace banner instead of append on turbolinks:load

app/models/concerns/mods_solr_document.rb, spec/requests/catalog_controller_request_spec.rb, spec/support/solr_documents/metadata_cloud_with_visibility.rb
co-authored-by: Martin Lovell <"martin.lovell@yale.edu">
co-authored-by: Lakeisha Robinson <"lakeisha.robinson@yale.edu">
=> more ladybird oai

app/models/concerns/mods_solr_document.rb, spec/requests/catalog_controller_request_spec.rb
Co-Authored-By: Martin Lovell <martin.lovell@yale.edu>
Original Code Image 
Modified Code Image
=> Fixed MODS object url link

package.json, yarn.lock
**Story**
We have more alerts!
**Acceptance**
=> Patch yarn postcss dependency

package.json, yarn.lock
=> Patching ws on blacklight

app/controllers/annotations_controller.rb, app/controllers/concerns/check_authorization.rb, config/routes.rb, spec/requests/annotation_request_spec.rb
Adds controller for full text service.
=> Add full text annotation service

package.json, yarn.lock
Merge main branch into fulltext branch with the latest releases as of June 4, 2021.
=> Mto f text

app/controllers/catalog_controller.rb, spec/system/view_fields_in_display_spec.rb
Separate multiple values with line break for title, alternative title, preferred citation.
=> Separate multiple values with line break

app/assets/stylesheets/customOverrides/show_page.scss
Story: As the product designer  I want the title to align with the picture box.  
Acceptance
-----
**The image on Production Server**
**Proposed Image**
=> Aligned title on single items page

app/controllers/catalog_controller.rb
- Create a new facet in Blacklight
=> Add has_fulltext_ssi as a facet

app/assets/stylesheets/customOverrides/advanced_search.scss, app/views/advanced/_advanced_search_fields.html.erb, spec/system/advanced_search_spec.rb
=> fulltext description advanced

app/views/advanced/_advanced_search_fields.html.erb, spec/system/advanced_search_spec.rb
=> add placeholder  to all fields and fulltext in the advanced search

spec/support/solr_documents/advanced_search_testing_only.rb, spec/system/advanced_search_spec.rb
Merge main to archival feature
=> Merge main2 fea arch wk29

app/assets/javascripts/application.js, app/assets/javascripts/show_more.js, app/assets/stylesheets/customOverrides/main.scss, app/helpers/blacklight_helper.rb, spec/system/show_page_spec.rb, spec/system/view_fields_in_search_spec.rb
Adds ellipsis button if hierarchy contains too many items.
(Hierarchy in images were manipulated to be large; the repeats in the hierarchy are not an error.)
=> 1454 collapse breadcrumbs

Gemfile.lock, app/views/application/landing.html.erb
Merge main to archival feature branch wk30
=> Merge main to arch feature wk30

app/controllers/catalog_controller.rb, spec/system/ancestor_title_hierarchy_spec.rb
Merge the management PR first: https://github.com/yalelibrary/yul-dc-management/pull/727
=> Add test for ancestor title hierarchy

app/controllers/catalog_controller.rb
Merge main to archival feature for week 32
=> Merge main to archival feature wk32

app/assets/stylesheets/customOverrides/constraints.scss, app/helpers/blacklight_helper.rb, app/views/catalog/_constraints.html.erb, spec/helpers/blacklight_helper_spec.rb, spec/system/view_facet_spec.rb
=> Revert collection title constraint dependency on repository

app/models/search_builder.rb, spec/requests/iiif_search_request_spec.rb
Include parent_ssi in fl parameter defaults.
=> Include parent_ssi in fl

yarn.lock
User Story
The application's dependencies should be up-to-date for week 36 of the year.
---
Acceptance
=> Patched blacklight is-svg WK36

yarn.lock
User Story
The application's dependencies should be up-to-date for week 36 of the year.
---
Acceptance
=> Patched blacklight minimist WK36

yarn.lock
User Story
The application's dependencies should be up-to-date for week 36 of the year.
---
Acceptance
=> Patched Blacklight xmodom

app/views/application/landing.html.erb
JP <jp@notch8.com>
**Story**
Stakeholders would like the homepage text updated to better describe the collections.
**Acceptance**
Yale Library's digital collections provide access to millions of digitized works and images. This site is a living database, and new materials are added regularly. Search or click the image below to begin your exploration.
There are Yale Library digital collections not available on this site. More information on these additional collections can be found here.
---
DEMO:
=> Changed the statement on the landing page

package.json, yarn.lock
**User Story**
The application's dependencies should be up-to-date for week 39 of the year.
---
**Acceptance**
=> Patched blacklight dependency i1635

app/assets/stylesheets/customOverrides/show_page.scss
Update  ancestortitle breadcrumb to  use Mallory font and match other metadata styling
[#1664]()
=> Changes font for ancestor breadcrumb

app/assets/stylesheets/customOverrides/show_page.scss, app/assets/stylesheets/theme/colors.scss, app/helpers/blacklight_helper.rb
Removes folder icon and replaces it with 'THIS ITEM' for the last item in the graphical hierarchy.
[#1658](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1658)
=> Formats last item in graphical hierarchy

app/assets/stylesheets/customOverrides/show_page.scss, app/controllers/catalog_controller.rb, spec/system/date_slider_spec.rb
**Story**
Change “Item Within Collection Hierarchy” to “Search for Additional Digitized Material in This Collection:”
**Acceptance**
----
**DEMO**
=> Changed object page archival context tree heading i1659

app/assets/stylesheets/customOverrides/show_page.scss
=> Modified text after the green box on object page

app/controllers/catalog_controller.rb, spec/system/view_facet_spec.rb
=> Add Grouping facet, if Collection Name facet is selected

README.md
Added a quick start guide to the readme and moved some sections to the yale wiki
=> updated blacklight readme

app/assets/stylesheets/customOverrides/show_page.scss
User Story
As the product designer, I want the Container / Volume data to appear across from the subtitle on the mobile screen.  
Current Design
Propose Design
=> Modified the alignment for the field and label

.circleci/config.yml
=> Runs tests in parallel on CircleCI

app/controllers/catalog_controller.rb, app/views/catalog/_uv.html.erb, spec/system/show_page_spec.rb
* Change OID label to Object ID (OID)
* Support image_id param to open UV to a specific canvas.
=> Change nomenclature from OID to ID

package.json, yarn.lock
**User Story**
The application's dependencies should be up-to-date for week 4 of the year.
---
**Acceptance**
=> 1860 Patched blacklight node-fetch

package.json, yarn.lock
**User Story**
The application's dependencies should be up-to-date for week 4 of the year.
---
**Acceptance**
=> 1860 Patched blacklight json-schema

package.json, yarn.lock
**User Story**
The application's dependencies should be up-to-date for week 4 of the year.
---
**Acceptance**
=> 1860 Patched blacklight postcss

package.json, yarn.lock
**User Story**
The application's dependencies should be up-to-date for week 4 of the year.
---
**Acceptance**
=> 1860 Patched blacklight three

app/helpers/blacklight_helper.rb, app/models/search_builder.rb, spec/system/search_fields_spec.rb, spec/system/show_page_spec.rb
Swap out the series title in ancestorTitles_tesim with the value in series_ssi.
The change is for display only.  
Facets and solr record has not been changed.
=> Swap out full series title in breadcrumb

config/uv/uv.html, public/uv/uv.html
Adds cache handling in uv.html for UV4 due to UV3 uv.html being cached.
[1994](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1994)
=> Fixes cache on uv.html for UV4

config/uv/uv.html, public/uv/uv.html
Fixes fullscreen vertical expand issue
[2042](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2042)
=> Fixes fullscreen vertical expand issue

app/assets/javascripts/application.js, spec/system/show_page_spec.rb
Fixes duplicate full text display. Testing to be completed on a separate ticket.
[2053](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2053)
https://user-images.githubusercontent.com/39319859/166838036-d2af6e01-4231-4902-b975-74d9527dddc7.mp4
=> UV4 Fix duplicate full text

config/uv/uv.html, public/uv/uv.html
Adds embedded: true property to allow embedding player into pages from other domains.
Check $UV_Iframe, which will be null when embedded in pages from other domains.
=> Add embedded option and check access to iframe element

config/locales/blacklight.en.yml, spec/system/user_authentication_spec.rb
Change Sign out to Log out in header.
[2089](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2089)
=> Change sign out to log out

Dockerfile, Gemfile
Update base image from 1.3.0 to 1.3.2 and Ruby version from 2.7.5 to 2.7.6.
[#2115](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2115)
=> Update base image and ruby version

config/initializers/assets.rb, spec/helpers/blacklight_helper_spec.rb
Adds version change to bust cache
[#2102](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2102)
=> Adds version change to bust cache

app/helpers/blacklight_helper.rb, spec/helpers/blacklight_helper_spec.rb
Adds loading="lazy" attribute to img tags for thumbnails
=> Use lazy loading for thumbnail images

Gemfile.lock
Reverts yalelibrary/yul-dc-blacklight#819
=> Revert "Bump rails-html-sanitizer from 1.4.2 to 1.4.3"

config/uv/uv.html, public/uv/uv.html
Add responsiveness of zoom and rotation options
[#2147](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2147)
=> Add responsiveness of zoom and rotation options

app/helpers/blacklight_helper.rb
Update conditional for ArchivesSpace base url
[#2016](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2016)
=> Update conditional for ArchivesSpace base url

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/support/solr_documents/advanced_search_testing_only.rb, spec/system/advanced_search_spec.rb, spec/system/search_fields_spec.rb
Adds the digitization note to the Advanced search fields.
[#2177](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2177)
=> Adds digitization note to advanced search

config/uv/uv.html, public/uv/uv.html
Removed formattedLocales from public and config uv.html  
#2081
=> Removed formattedLocales from uv

app/views/application/landing.html.erb, app/views/layouts/blacklight/base.html.erb
Adds script to header content for analytics.
[#2297](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2297)
=> Adds siteimprove script to head content

app/views/application/landing.html.erb
Fixed link to include the creator A-Z sorting and other important details.
[#2324](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/gh/yalelibrary/yul-dc/2324)
=> Replace link

app/views/application/landing.html.erb, app/views/layouts/blacklight/base.html.erb
Added SRI Subresource Hash to the SiteImprove link  
[2328](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2328)
=> Added SRI hash

app/views/application/landing.html.erb, app/views/layouts/blacklight/base.html.erb
Reverts yalelibrary/yul-dc-blacklight#856
=> Revert "Added SRI hash"

spec/controllers/omniauth_callbacks_controller_spec.rb, spec/services/s3_service_spec.rb, spec/system/modal_component_spec.rb
This MR will increase code coverage to 90.48%.
[#2343](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/gh/yalelibrary/yul-dc/2343)
=> Increases code coverage

Gemfile, Gemfile.lock
Blacklight upgrade to 7.33  
[2352](https://github.com/orgs/yalelibrary/projects/1/views/1?pane=issue&itemId=20512741)
=> blacklight gemfile to 7.33

Gemfile, Gemfile.lock
Downgrade blacklight-gallery to a working version:
=> Downgrade blacklight-gallery version

app/controllers/download_original_controller.rb, spec/requests/download_original_spec.rb
=> Converts post request to a get

app/views/download_original/tiff_staged.html.erb
Adds further instructions for users in the download original html tab.  
[2445](https://github.com/orgs/yalelibrary/projects/1/views/1?pane=issue&itemId=24480071)
=> Adds further user instructions to staged download page

app/assets/javascripts/download_original.js
Increases tab close time from 10 seconds to 60 seconds.
=> increase tab close time to 60 seconds

public/robots.txt
Disallow:
* PDFs
* IIIF manifests
* Mirador page
=> Add PDF, IIIF, Mirador to robots.txt

app/controllers/catalog_controller.rb
Adds a return statement to a redirect_to to prevent double rendering.  
[2461](https://github.com/orgs/yalelibrary/projects/1/views/1?pane=issue&itemId=25662442)
=> add return to redirect

.circleci/config.yml
Upgrades Docker Convenience Image  
[2472](https://github.com/orgs/yalelibrary/projects/1/views/1?pane=issue&itemId=26325652)
=> upgrades docker convenience image

config/uv/uv.html, public/uv/uv.css, public/uv/uv.html
Adds css font-family for UV config
=> adds css rules to uv config

Gemfile, Gemfile.lock, app/controllers/download_original_controller.rb, app/controllers/pdfs_controller.rb, app/lib/aws_metrics.rb
Adds Cloudwatch metrics for TIFF and PDF downloads.   Requires new feature flag to activate.
=> Adds Cloudwatch metrics for TIFF and PDF downloads

app/controllers/omniauth_callbacks_controller.rb, app/models/user.rb, db/migrate/20230926171133_add_sub_and_net_id.rb, db/migrate/20230926201727_add_index_to_net_id_sub.rb, db/schema.rb, spec/controllers/omniauth_callbacks_controller_spec.rb, spec/factories/users.rb
Adds NetId and Sub to Users table.  
Also adds index to make unique: true  
Adds presence validation to sub to ensure sub is not null.
=> adds netid and sub to users table

.dockerignore
Same yarn.lock removal that we did in Management. 
[2542](https://github.com/orgs/yalelibrary/projects/1/views/1?filterQuery=&pane=issue&itemId=33131707)
=> comments out yarn.lock

app/assets/stylesheets/customOverrides/advanced_search.scss, app/views/advanced/_advanced_search_help.html.erb
Adds Moe Information section with link to new Help Guide:
=> (MERGE SECOND) adds More Information section to advanced search

app/assets/stylesheets/customOverrides/landing.scss
Adjusts media queries for new content in hero banner
=> media queries for new landing content

app/assets/stylesheets/customOverrides/help_guide.scss
Help Guide font changed to Mallory-Medium
=> Help Guide font

app/controllers/catalog_controller.rb, app/helpers/blacklight_helper.rb
* format morris record url
* custom morris_link for morris records
* rubocop
---------
=> Merge SierraFeatureBranch into main

app/controllers/concerns/check_authorization.rb, app/helpers/access_helper.rb, app/views/catalog/_show_main_content.html.erb, spec/factories/users.rb, spec/requests/open_with_permission_spec.rb, spec/system/show_page_spec.rb
Retrieves User API information and displays OwP objects depending on login and access status.  
Not signed in:  
Signed in without access:
=> 2653 parent object page owp

app/controllers/catalog_controller.rb, app/controllers/permission_requests_controller.rb, app/helpers/access_helper.rb, app/views/catalog/request_confirmation.html.erb, spec/system/permission_requests_spec.rb
Updates the confirmation page to use data from the management api.
[#2656](https://github.com/orgs/yalelibrary/projects/1/views/1?pane=issue&itemId=40636754)
=> Adds management calls for confirmation page

app/helpers/access_helper.rb, app/views/catalog/_show_main_content.html.erb, spec/requests/open_with_permission_spec.rb, spec/requests/permission_requests_spec.rb, spec/system/show_page_spec.rb
Displays pending request notice on object showpage if user has a pending request to the object.
=> 2657 pending request notification

app/assets/stylesheets/customOverrides/show_page.scss, app/controllers/catalog_controller.rb, app/controllers/permission_requests_controller.rb, app/helpers/access_helper.rb, app/views/catalog/request_form.html.erb, app/views/catalog/terms_and_conditions.html.erb, app/views/shared/_search_bar.html.erb, config/routes.rb, spec/requests/open_with_permission_spec.rb, spec/system/show_page_spec.rb
Retrieves Terms and Conditions from Management if the user has not agreed to the terms. Agreeing to the terms records the terms agreement on Management and then renders the request form.  
Terms page:
=> Terms and Conditions

app/controllers/catalog_controller.rb, app/helpers/access_helper.rb, config/routes.rb
Fixes Auth Token missing bug  
Fixes missing request user error when retrieving OwP permissions.
=> 2654 terms bug

app/assets/stylesheets/customOverrides/index_gallery.scss, spec/system/show_page_spec.rb
Moves the bookmark checkbox above image thumbnails on gallery views.
=> Bookmark Gallery View

app/helpers/access_helper.rb, app/views/catalog/_show_main_content.html.erb, spec/requests/open_with_permission/owp_object_show_page_request_spec.rb, spec/system/show_page_spec.rb
Allows access for permission set approvers/admins
=> 2766 owp admin access

app/helpers/access_helper.rb, spec/requests/open_with_permission/owp_object_show_page_request_spec.rb, spec/system/show_page_spec.rb
Reverts yalelibrary/yul-dc-blacklight#990
=> Revert "2766 owp admin access"

app/controllers/application_controller.rb, app/controllers/catalog_controller.rb, app/controllers/permission_requests_controller.rb, app/helpers/access_helper.rb, spec/requests/open_with_permission/create_permission_requests_request_spec.rb, spec/requests/open_with_permission/owp_object_show_page_request_spec.rb, spec/system/fulltext_search_spec.rb, spec/system/open_with_permission/permission_request_confirmation_page_spec.rb, spec/system/open_with_permission/user_requests_table_page_spec.rb, spec/system/show_page_spec.rb
Replaces true/false request_status with Approved/Denied
=> replaces request_status with approved/denied

app/views/shared/_user_util_links.html.erb
Adds "Access Requests" to header and changes "Bookmarks" to "Saved Items"
=> Access request header

config/locales/blacklight.en.yml, spec/system/header_spec.rb
Updates "Bookmarks" language to "Saved Items"  
Bookmark page:  
Search results page:  
Parent Object page:
=> Update bookmarks language

config/locales/blacklight.en.yml
Adds"Saved item" vocab to a few more instances of Bookmarks
=> Bookmarks -> Saved items

app/assets/stylesheets/customOverrides/advanced_search.scss, app/assets/stylesheets/helpers/breakpoints.scss
Adds media query to make advanced search All/Any button wider.  
Before:  
After:
=> Mobile Dropdown

app/controllers/permission_requests_controller.rb, app/views/catalog/_show_main_content.html.erb, spec/requests/open_with_permission/owp_object_show_page_request_spec.rb
Updates confirmation messages.
=> updates confirmation messages

app/views/permission_requests/index.html.erb
Fixes Title sorting on the requests table
=> Sort Title

app/assets/stylesheets/customOverrides/show_page.scss
Adds top margin for aspace tree in mobile devices.
=> adds margin for mobile aspace tree

app/controllers/download_original_controller.rb
Addresses the missing template error by removing the file type
=> MissingTemplate error

app/assets/stylesheets/customOverrides/show_page.scss
Adds xmini breakpoint for the ASpace tree css.
=> ASpace Tree spacing

Dockerfile
[#2785](https://github.com/yalelibrary/YUL-DC/issues/2785)
=> Update camerata version

app/controllers/download_original_controller.rb
Attempt to fix the large tiff downloads from timing out
=> Large TIFF download

app/controllers/download_original_controller.rb
Reverts yalelibrary/yul-dc-blacklight#1033
=> Revert "Large TIFF download"

app/controllers/omniauth_callbacks_controller.rb
separates non-yale login and yale login logic
=> Non-Yale user sign in

app/controllers/catalog_controller.rb, app/controllers/permission_requests_controller.rb, app/helpers/access_helper.rb, spec/requests/open_with_permission/create_permission_requests_request_spec.rb, spec/requests/open_with_permission/owp_object_show_page_request_spec.rb, spec/system/fulltext_search_spec.rb, spec/system/open_with_permission/permission_request_confirmation_page_spec.rb, spec/system/open_with_permission/user_requests_table_page_spec.rb, spec/system/show_page_spec.rb
Adds an auth token for Open with Permission requests.
[#2877](https://github.com/yalelibrary/YUL-DC/issues/2877)
=> Add OwP auth token

app/views/permission_requests/index.html.erb
"Request Date" sorting in Access Requests now sorts correctly.
=> Request Date sorting

app/controllers/permission_requests_controller.rb, app/helpers/access_helper.rb, app/views/permission_requests/index.html.erb
Add guard for missing call number, protections against unauthorized access and adds header to get requests.
[#2877](https://github.com/yalelibrary/YUL-DC/issues/2877)
=> Adds guards for OwP headers and missing metadata

app/controllers/omniauth_callbacks_controller.rb, app/views/catalog/_ai_link.html.erb, app/views/catalog/_show.html.erb, app/views/catalog/_show_main_content.html.erb, spec/system/show_page_spec.rb
Shows a link to the Collections AI site only to users in the requisite authentication group.
=> Show AI tool link to authorized users

app/helpers/access_helper.rb
Expands response check by checking the body of the json response instead of just the response.
=> No Terms bug

app/views/help_guide.html.erb, config/locales/submenu.en.yml, spec/system/header_spec.rb
Updates Special Collection Guide URL.  
Also updates the link in the help guide.
=> updates special collection guide url

app/controllers/catalog_controller.rb, spec/system/advanced_search_spec.rb
Adds `date_ssim` as a fallback sorting field from `year_isim`
=> fix asc oid sorting

app/controllers/omniauth_callbacks_controller.rb
Add a second group eligible to see the link to the AI tool.
=> Add authorized group for AI

Gemfile, Gemfile.lock, spec/system/access_restrictions_spec.rb, spec/system/advanced_search_spec.rb
Upgrade to Bootstrap version 5.3.3
=> Upgrade to Bootstrap v5.3.3

app/assets/stylesheets/customOverrides/landing.scss, app/assets/stylesheets/customOverrides/pagination.scss
Additional style fixes post bootstrap 5 upgrade.
fixed button alignment
fixed pagination
=> Fixes styling

app/controllers/catalog_controller.rb, spec/system/sort_in_search_spec.rb
=> capitalize Relevance

app/assets/stylesheets/customOverrides/advanced_search.scss, app/assets/stylesheets/customOverrides/constraints.scss, app/assets/stylesheets/customOverrides/facets.scss, app/assets/stylesheets/customOverrides/header.scss, app/assets/stylesheets/customOverrides/index_gallery.scss, app/assets/stylesheets/customOverrides/landing.scss, app/assets/stylesheets/customOverrides/pagination.scss, app/assets/stylesheets/customOverrides/show_page.scss, app/views/catalog/_constraints.html.erb, spec/system/view_facet_spec.rb
Continuation of styling fixes post upgrade to Bootstrap 5.
=> Restore styling 

app/assets/javascripts/application.js
Updates site source for banner for non production environments.
[#3038](https://github.com/yalelibrary/YUL-DC/issues/3038)
=> Use test banner site for non production environments

Gemfile.lock, app/helpers/blacklight_helper.rb
Updates logic to prevent duplicate links. Also includes update from main.
[#3022](https://github.com/yalelibrary/YUL-DC/issues/3022)
=> Update identifier links

app/controllers/concerns/blacklight/search_context.rb
Changed blacklist -> blocklist
=> Update Terms language

app/assets/stylesheets/customOverrides/show_page.scss, app/controllers/catalog_controller.rb, app/views/catalog/_uv.html.erb
Adds the Sensitive Materials overlay to objects that have sensitive materials.  
Desktop:  
Mobile:
=> adds sensitive materials overlay

Dockerfile, README.md
Cleaning up references to Dynatrace.
[#3100](https://github.com/yalelibrary/YUL-DC/issues/3100)
=> Removes reference to Dynatrace

app/views/catalog/_uv.html.erb
=> Sensitive Materials text rework

app/assets/stylesheets/customOverrides/show_page.scss
Aligns Container/Volume when aspace tree is present
=> aligns container/volume

app/controllers/catalog_controller.rb, app/helpers/blacklight_helper.rb, spec/helpers/blacklight_helper_spec.rb, spec/system/view_fields_in_display_spec.rb
Toward [#3078](https://github.com/yalelibrary/YUL-DC/issues/3078)
=> Add rel=nofollow to links that trigger new searches

README.md
Adds a link to the readme for the new sitemap generation article.
[#3089](https://github.com/yalelibrary/YUL-DC/issues/3089)
=> Adds link to sitemap documentation
